// src/scenarios/metabolic/index.ts — 8 metabolic scenarios
import type { ScenarioDefinition } from '../../store/useScenarioStore';

export const metabolicScenarios: ScenarioDefinition[] = [
  {
    id: 'dka_severe',
    category: 'metabolic',
    name: 'CAD Severa — pH 6.98',
    description: 'Cetoacidosis diabética grave (pH 6.98, bicarb 4 mEq/L, gap 36). Trigger: infección urinaria. Hipokalemia peligrosa (K⁺ 2.8).',
    baseSeverity: 0.80,
    tags: ['CAD', 'DKA', 'Cetoacidosis', 'Insulina IV', 'Hipokalemia'],
    pathologyConfigs: [
      { domain: 'sepsis', subtype: 'metabolic_dka', baseSeverity: 0.75 },
    ],
    initialVitals: { heartRate: 128, systolicBP: 92, diastolicBP: 58, meanArterialPressure: 69, spo2: 97, pH: 6.98, hco3: 4, baseExcess: -26, lactate: 3.4, temperature: 38.8 },
    isVentilatorConnected: false,
    clinicalNotes: 'Insulina 0.1 UI/kg/h IV. Reposición K⁺ antes de iniciar insulina (umbral 3.5). SF 1L/h primeras 2h → SF 250-500 mL/h. Bicarb solo si pH < 6.9.',
    references: ['Umpierrez GE Diabetologia 2024', 'Kitabchi AE Diabetes Care 2009'],
  },
  {
    id: 'hhs',
    category: 'metabolic',
    name: 'Estado Hiperosmolar Hiperglucémico',
    description: 'EHH: glucemia 1240 mg/dL, osmolaridad 388 mOsm/kg, Na 158 mEq/L, sin cetosis. Paciente de 78 años con DM2 descompensada. Confusión profunda.',
    baseSeverity: 0.75,
    tags: ['EHH', 'HHS', 'Hiperosmolar', 'DM2', 'Rehidratación'],
    pathologyConfigs: [
      { domain: 'sepsis', subtype: 'metabolic_hhs', baseSeverity: 0.70 },
    ],
    initialVitals: { heartRate: 112, systolicBP: 100, diastolicBP: 62, meanArterialPressure: 75, spo2: 96, gcs: 10, temperature: 37.8, urineOutput: 0.15 },
    isVentilatorConnected: false,
    clinicalNotes: 'SF 0.9% 1L/h primeras 4h. Meta osmolaridad < 310 mOsm/kg en 48h. Insulina iniciar cuando glucemia < 300 mg/dL (evitar caída rápida). Heparina antitrombótica.',
    references: ['Stoner GD Am Fam Physician 2017', 'ADA Standards 2024'],
  },
  {
    id: 'severe_hyponatremia',
    category: 'metabolic',
    name: 'Hiponatremia Grave — Síntomas Severos',
    description: 'Hiponatremia grave (Na⁺ 108 mEq/L) con convulsiones activas en SIADH por cáncer pulmonar. Corrección urgente con NaCl 3% bolus.',
    baseSeverity: 0.78,
    tags: ['Hiponatremia', 'SIADH', 'Convulsiones', 'NaCl 3%'],
    pathologyConfigs: [
      { domain: 'neuroCritical', subtype: 'severe_hyponatremia', baseSeverity: 0.75 },
    ],
    initialVitals: { heartRate: 108, systolicBP: 128, diastolicBP: 78, meanArterialPressure: 95, gcs: 8, temperature: 37.0 },
    isVentilatorConnected: false,
    clinicalNotes: 'NaCl 3% 150 mL en 20 min × 3 dosis si síntomas severos. Meta +5 mEq/L en 1h. Nunca > +10 mEq/L en 24h ni > +18 mEq/L en 48h (riesgo mielinolisis).',
    references: ['Spasovski G BMJ 2014 (ERC-EDTA)', 'Sterns RH NEJM 2015'],
  },
  {
    id: 'tumor_lysis_syndrome',
    category: 'metabolic',
    name: 'Síndrome de Lisis Tumoral',
    description: 'SLT espontáneo en linfoma de Burkitt post-primer ciclo QT. Hiperkalemia (K⁺ 7.2), hiperfosfatemia, hipocalcemia, AKI aguda. Riesgo arritmia.',
    baseSeverity: 0.82,
    tags: ['SLT', 'Linfoma', 'Hiperkalemia', 'AKI', 'Rasburicasa'],
    pathologyConfigs: [
      { domain: 'sepsis', subtype: 'tls', baseSeverity: 0.80 },
    ],
    initialVitals: { heartRate: 118, systolicBP: 102, diastolicBP: 65, meanArterialPressure: 77, spo2: 96, urineOutput: 0.2, creatinine: 4.2 },
    isVentilatorConnected: false,
    clinicalNotes: 'Rasburicasa 0.2 mg/kg (uricemia). Hiperhidratación forzada 200 mL/h. Kayexalato si K⁺ > 6. Hemodiálisis urgente si K⁺ > 6.5 + cambios ECG.',
    references: ['Cairo MS Br J Haematol 2010', 'Howard SC NEJM 2011'],
  },
  {
    id: 'thyroid_storm',
    category: 'metabolic',
    name: 'Tormenta Tiroidea — Burch-Wartofsky 65',
    description: 'Tormenta tiroidea (Burch-Wartofsky 65). T3/T4 extremadamente elevados. Hiperpirexia 40.8°C, taquicardia 168 bpm, IC de alto gasto. FA con RVR.',
    baseSeverity: 0.85,
    tags: ['Tormenta Tiroidea', 'Tirotoxicosis', 'Propranolol', 'PTU'],
    pathologyConfigs: [
      { domain: 'cardio', subtype: 'thyroid_storm', baseSeverity: 0.85 },
    ],
    initialVitals: { heartRate: 168, systolicBP: 178, diastolicBP: 88, meanArterialPressure: 118, temperature: 40.8, spo2: 95, lactate: 2.2 },
    isVentilatorConnected: false,
    clinicalNotes: 'Propiltiouracilo 500-1000mg CARGA → 250mg c/4h. KI 1h después. Dexametasona 2mg c/6h. Propranolol IV/VO. Paracetamol (NO aspirina).',
    references: ['Burch HB JCEM 1993', 'Ross DS Thyroid 2016 (ATA/AAA)'],
  },
  {
    id: 'adrenal_crisis',
    category: 'metabolic',
    name: 'Crisis Adrenal — Shock Refractario',
    description: 'Insuficiencia suprarrenal primaria descompensada por infección intercurrente. Shock refractario a vasopresores. Hiponatremia + hiperkalemia.',
    baseSeverity: 0.80,
    tags: ['Adrenal', 'Cortisol', 'Shock', 'Hidrocortisona', 'Mineralocorticoide'],
    pathologyConfigs: [
      { domain: 'sepsis', subtype: 'adrenal_crisis', baseSeverity: 0.78 },
    ],
    initialVitals: { heartRate: 128, systolicBP: 68, diastolicBP: 40, meanArterialPressure: 49, temperature: 38.2, lactate: 4.2, urineOutput: 0.1 },
    isVentilatorConnected: false,
    clinicalNotes: 'Hidrocortisona 100mg IV bolo URGENTE → 50mg c/6h. No esperar cortisol sérico. Fluidos. Fludrocortisona 0.1mg VO.',
    references: ['Bornstein SR JCEM 2016 (Endocrine Soc)', 'Rushworth RL Med J Aust 2017'],
  },
  {
    id: 'rhabdomyolysis_severe',
    category: 'metabolic',
    name: 'Rabdomiólisis Severa — AKI estadio 3',
    description: 'Rabdomiólisis grave (CPK 180000 UI/L) post-síndrome de aplastamiento. AKI estadio 3. Hiperkalemia 6.8. Síndrome compartimental de pierna derecha.',
    baseSeverity: 0.82,
    tags: ['Rabdomiólisis', 'AKI', 'Crush', 'CPK', 'Síndrome Compartimental'],
    pathologyConfigs: [
      { domain: 'polytrauma', subtype: 'crush_rhabdo', baseSeverity: 0.80 },
    ],
    initialVitals: { heartRate: 118, systolicBP: 98, diastolicBP: 62, meanArterialPressure: 74, spo2: 97, urineOutput: 0.08, creatinine: 6.8 },
    isVentilatorConnected: false,
    clinicalNotes: 'Hidratación agresiva 1-1.5 L/h SF (meta diuresis 200-300 mL/h). Bicarbonato para alcalinizar orina (pH urinario > 6.5). Fasciotomía urgente si síndrome compartimental.',
    references: ['Sauret JM Am Fam Physician 2002', 'Bosch X Ann Intern Med 2009'],
  },
  {
    id: 'refractory_metabolic_acidosis',
    category: 'metabolic',
    name: 'Acidosis Metabólica Refractaria — CRRT',
    description: 'Acidosis metabólica grave (pH 7.05, HCO₃ 7) refractaria en AKI oligúrica por sepsis. Indicación de CRRT urgente.',
    baseSeverity: 0.86,
    tags: ['Acidosis', 'CRRT', 'AKI', 'Bicarbonato', 'Diálisis'],
    pathologyConfigs: [
      { domain: 'sepsis', subtype: null, baseSeverity: 0.85 },
    ],
    initialVitals: { heartRate: 130, systolicBP: 78, diastolicBP: 48, meanArterialPressure: 58, pH: 7.05, hco3: 7, baseExcess: -22, lactate: 6.2, urineOutput: 0.0, creatinine: 7.8 },
    isVentilatorConnected: true,
    ventilatorPreset: { fio2: 0.55, peep: 8 },
    clinicalNotes: 'CVVHDF con citrato + calcio. Bicarbonato IV solo si pH < 7.10 + K⁺ > 6.5 o compromiso hemodinámico. Vasopresina si shock refractario.',
    references: ['Kellum JA Semin Nephrol 2015', 'ADQI 2016 Consensus'],
  },
];
