// src/scenarios/sepsis_ext/index.ts — 8 extended sepsis scenarios
import type { ScenarioDefinition } from '../../store/useScenarioStore';

export const sepsisExtScenarios: ScenarioDefinition[] = [
  {
    id: 'pneumonia_nosocomial_mrsa',
    category: 'sepsis',
    name: 'Neumonía Nosocomial — MRSA',
    description: 'Neumonía asociada a ventilador (NAV) por Staphylococcus aureus meticilino-resistente. D8 ARM. Deterioro gasométrico. SDRA moderado.',
    baseSeverity: 0.80,
    tags: ['NAV', 'MRSA', 'ARM', 'SDRA', 'Vancomicina'],
    pathologyConfigs: [
      { domain: 'pneumonia', subtype: 'mrsa', baseSeverity: 0.80 },
      { domain: 'ards', subtype: null, baseSeverity: 0.62 },
      { domain: 'sepsis', subtype: null, baseSeverity: 0.65 },
    ],
    initialVitals: { heartRate: 118, systolicBP: 88, diastolicBP: 52, meanArterialPressure: 64, spo2: 88, pfRatio: 118, ardsActive: true, ardsSeverityLevel: 'MODERATE', temperature: 39.4, lactate: 3.2 },
    isVentilatorConnected: true,
    ventilatorPreset: { fio2: 0.70, peep: 10, vt: 380 },
    clinicalNotes: 'Vancomicina + ajuste por AUC (25-35 mg×h/L). Tigeciclina si VRSA. Broncoscopia BAL + cultivo cuantitativo.',
    references: ['Torres A JAMA 2017', 'Shorr AF Chest 2006'],
  },
  {
    id: 'uti_pyelonephritis_sepsis',
    category: 'sepsis',
    name: 'Urosepsis — Pielonefritis Complicada',
    description: 'Shock séptico de foco urinario. ESBL E. coli en hemocultivos. Pielonefritis enfisematosa con obstrucción ureteral bilateral. Drenaje urgente.',
    baseSeverity: 0.78,
    tags: ['Urosepsis', 'ESBL', 'E. coli', 'Shock', 'Drenaje Urológico'],
    pathologyConfigs: [
      { domain: 'sepsis', subtype: null, baseSeverity: 0.78 },
    ],
    initialVitals: { heartRate: 124, systolicBP: 78, diastolicBP: 48, meanArterialPressure: 58, temperature: 39.8, lactate: 4.4, urineOutput: 0.1, creatinine: 3.2 },
    isVentilatorConnected: false,
    clinicalNotes: 'Meropenem 1g c/8h (ESBL). Nefrostomía percutánea urgente. Fluidos + vasopresores si MAP < 65. Cultivos antes de ATB.',
    references: ['Singer M Sepsis-3 JAMA 2016', 'Wen Y PLoS ONE 2025 (ESBL uti)'],
  },
  {
    id: 'peritonitis_fecal',
    category: 'sepsis',
    name: 'Peritonitis Fecal Post-Anastomosis',
    description: 'Dehiscencia anastomótica 72h post-hemicolectomía. Peritonitis fecal. Laparotomía urgente de control de daños. Abdomen abierto con VAC.',
    baseSeverity: 0.88,
    tags: ['Peritonitis', 'Abdomen Abierto', 'Shock', 'Cirugía Control Daños'],
    pathologyConfigs: [
      { domain: 'sepsis', subtype: null, baseSeverity: 0.88 },
    ],
    initialVitals: { heartRate: 132, systolicBP: 74, diastolicBP: 44, meanArterialPressure: 54, temperature: 40.0, lactate: 6.8, urineOutput: 0.1 },
    isVentilatorConnected: true,
    ventilatorPreset: { fio2: 0.65, peep: 8 },
    clinicalNotes: 'Piperacilina-tazobactam + metronidazol. Noradrenalina + vasopresina si shock persistente. Relaparotomía 48-72h para cierre diferido.',
    references: ['Sartelli M Surg Infect 2020 (WSES)', 'De Waele JJ Intensive Care Med 2014'],
  },
  {
    id: 'necrotizing_fasciitis',
    category: 'sepsis',
    name: 'Fascitis Necrotizante — Tipo II',
    description: 'Fascitis necrotizante tipo II (estreptococo grupo A) de extremidad inferior. LRINEC ≥ 8. Shock tóxico estreptocócico. Desbridamiento quirúrgico urgente.',
    baseSeverity: 0.90,
    tags: ['Fascitis', 'GAS', 'Shock Tóxico', 'Cirugía Urgente'],
    pathologyConfigs: [
      { domain: 'sepsis', subtype: 'toxic_shock', baseSeverity: 0.90 },
    ],
    initialVitals: { heartRate: 136, systolicBP: 68, diastolicBP: 42, meanArterialPressure: 51, temperature: 40.4, lactate: 7.2, urineOutput: 0.08 },
    isVentilatorConnected: true,
    clinicalNotes: 'Penicilina G + clindamicina (efecto Eagle inverso). Desbridamiento 6-12h urgencia. IVIG 2g/kg discutido. HBOT no retrasa cirugía.',
    references: ['Hakkarainen TW Curr Probl Surg 2014', 'Stevens DL NEJM 2020'],
  },
  {
    id: 'catheter_related_bsi',
    category: 'sepsis',
    name: 'BSI Relacionada a CVC — Candida',
    description: 'Sepsis por candidemia (C. albicans) asociada a CVC en paciente post-QT. APACHE II 18. Retiro de catéter + equinocandina urgente.',
    baseSeverity: 0.72,
    tags: ['Candidemia', 'CVC', 'Equinocandina', 'Antifúngico'],
    pathologyConfigs: [
      { domain: 'sepsis', subtype: 'fungal', baseSeverity: 0.72 },
    ],
    initialVitals: { heartRate: 114, systolicBP: 85, diastolicBP: 52, meanArterialPressure: 63, temperature: 38.8, lactate: 2.8 },
    isVentilatorConnected: false,
    clinicalNotes: 'Caspofungina 70mg carga → 50mg/d. Retirar CVC urgente. Fondo de ojo (endoftalmitis). Eco abdominal. Cultivos de seguimiento 48h.',
    references: ['Pappas PG IDSA 2016', 'Kullberg BJ Lancet Infect Dis 2015'],
  },
  {
    id: 'meningococcemia',
    category: 'sepsis',
    name: 'Meningococemia Fulminante',
    description: 'Infección meningocócica (Neisseria meningitidis serogrupo C) con petequias progresando a púrpura. Coagulación intravascular diseminada. SOFA 12.',
    baseSeverity: 0.92,
    tags: ['Meningococo', 'CID', 'Púrpura', 'Shock', 'ARM'],
    pathologyConfigs: [
      { domain: 'sepsis', subtype: 'meningococcal', baseSeverity: 0.92 },
    ],
    initialVitals: { heartRate: 148, systolicBP: 62, diastolicBP: 38, meanArterialPressure: 46, temperature: 40.2, lactate: 8.2, urineOutput: 0.05 },
    isVentilatorConnected: true,
    clinicalNotes: 'Ceftriaxona 4g/d IV. Dexametasona si meningitis coexistente. CID: PFC + plaquetas. Profilaxis contactos rifampicina/ciprofloxacino.',
    references: ['Emonts M Lancet 2015', 'Vieusseux 1805 (descripción clásica)'],
  },
  {
    id: 'multifocal_septic_shock_mof',
    category: 'sepsis',
    name: 'Shock Séptico + MOF (SOFA 17)',
    description: 'Shock séptico de foco abdominal con fallo multiorgánico establecido: AKI estadio 3, SDRA grave, disfunción hepática, CID. SOFA 17. Máximo soporte.',
    baseSeverity: 0.95,
    tags: ['MOF', 'SOFA Alto', 'Shock', 'CRRT', 'ARM'],
    pathologyConfigs: [
      { domain: 'sepsis', subtype: null, baseSeverity: 0.95 },
      { domain: 'ards', subtype: null, baseSeverity: 0.85 },
    ],
    initialVitals: { heartRate: 136, systolicBP: 68, diastolicBP: 42, meanArterialPressure: 51, spo2: 84, pfRatio: 68, ardsActive: true, ardsSeverityLevel: 'SEVERE', lactate: 9.8, urineOutput: 0.05, creatinine: 5.4 },
    isVentilatorConnected: true,
    ventilatorPreset: { fio2: 0.95, peep: 14 },
    clinicalNotes: 'CRRT con CVVHDF. Noradrenalina + vasopresina + hidrocortisona. Discusión pronóstica con familia. Objetivo: reducción SOFA < 10 en 72h.',
    references: ['Singer M Sepsis-3 JAMA 2016', 'SSC 2021 Evans L et al.'],
  },
  {
    id: 'pseudomonas_icu_pneumonia',
    category: 'sepsis',
    name: 'Neumonía Pseudomonas MDR — Pan-Resistente',
    description: 'Neumonía por Pseudomonas aeruginosa pan-resistente (PDR) en paciente con bronquiectasias. XDR con resistencia a colistina. Ceftazidima-avibactam + aztreonam discutido.',
    baseSeverity: 0.85,
    tags: ['Pseudomonas', 'MDR', 'PDR', 'ARM', 'Antibióticos de Rescate'],
    pathologyConfigs: [
      { domain: 'pneumonia', subtype: 'pseudomonas_xdr', baseSeverity: 0.85 },
      { domain: 'sepsis', subtype: null, baseSeverity: 0.70 },
      { domain: 'ards', subtype: null, baseSeverity: 0.58 },
    ],
    initialVitals: { heartRate: 125, systolicBP: 84, diastolicBP: 50, meanArterialPressure: 61, spo2: 86, pfRatio: 102, ardsActive: true, ardsSeverityLevel: 'SEVERE', temperature: 39.6, lactate: 3.8 },
    isVentilatorConnected: true,
    ventilatorPreset: { fio2: 0.80, peep: 12 },
    clinicalNotes: 'Ceftazidima-avibactam 2.5g c/8h + aztreonam 2g c/8h. Consulta infecto urgente. Ajuste por ESKD. Desbridamiento si foco identificado.',
    references: ['Tamma PD IDSA 2022 (AMR Guidance)', 'Shields RK AAC 2018'],
  },
];
