// src/scenarios/trauma_burn_ext/index.ts — 5 extended trauma/burn scenarios
import type { ScenarioDefinition } from '../../store/useScenarioStore';

export const traumaBurnExtScenarios: ScenarioDefinition[] = [
  {
    id: 'polytrauma_class_iii_ext',
    category: 'trauma',
    name: 'Politrauma Clase III — Control de Daños',
    description: 'Politrauma severo (ISS 38). Hemorragia Clase III (2200 mL perdidos). Lesión hepática grado IV + fractura pélvica inestable. Laparotomía control daños en curso.',
    baseSeverity: 0.90,
    tags: ['Politrauma', 'Hemorragia', 'Laparotomía', 'Transfusión', 'ATLS'],
    pathologyConfigs: [
      { domain: 'hemorrhagicShock', subtype: 'class_iii', baseSeverity: 0.90 },
      { domain: 'polytrauma', subtype: null, baseSeverity: 0.82 },
    ],
    initialVitals: { heartRate: 142, systolicBP: 72, diastolicBP: 44, meanArterialPressure: 53, lactate: 7.8, spo2: 93, urineOutput: 0.1 },
    isVentilatorConnected: true,
    ventilatorPreset: { fio2: 0.80, peep: 6 },
    initialBloodVolumeMl: 2500,
    clinicalNotes: 'Transfusión masiva 1:1:1 (GRE:PFC:PLT). Ácido tranexámico < 3h. TXA si CRASH-2 positivo. Sonda Foley + temperatura activa. pH goal > 7.25.',
    references: ['ATLS 10th ed 2018', 'CRASH-2 Lancet 2010', 'Holcomb JB JAMA 2015 (PROPPR)'],
  },
  {
    id: 'burn_40_tbsa',
    category: 'burns',
    name: 'Quemadura 40% SCT — Llama + Inhalación',
    description: 'Quemadura llama 40% SCT (30% 2° profundo, 10% 3°). Lesión inhalatoria confirmada. No ARM aún. Reanimación Parkland. Riesgo edema vía aérea progresivo.',
    baseSeverity: 0.84,
    tags: ['Quemadura', '40% SCT', 'Inhalación', 'Parkland', 'ARM Precoz'],
    pathologyConfigs: [
      { domain: 'burn', subtype: 'flame_inhalation', baseSeverity: 0.84 },
    ],
    initialVitals: { heartRate: 128, systolicBP: 98, diastolicBP: 62, meanArterialPressure: 74, spo2: 94, temperature: 37.8, urineOutput: 0.3 },
    isVentilatorConnected: false,
    recommendedRespSupport: 'hfnc',
    clinicalNotes: 'Parkland: 4 mL/kg/% SCT × 24h (½ primera 8h). Meta diuresis 0.5-1 mL/kg/h. Intubación precoz si estridor, hollín en vía aérea.',
    references: ['Jeschke MG NEJM 2020', 'Palmieri TL J Trauma 2010'],
  },
  {
    id: 'burn_inhalation_injury',
    category: 'burns',
    name: 'Lesión Inhalatoria Aislada — SDRA Inhalatorio',
    description: 'Lesión inhalatoria severa por incendio en espacio confinado. SpCO 42%. ARM urgente. Quemaduras cutáneas < 10% SCT.',
    baseSeverity: 0.80,
    tags: ['Inhalación', 'CO', 'SpCO', 'ARM', 'O2 100%'],
    pathologyConfigs: [
      { domain: 'burn', subtype: 'inhalation_only', baseSeverity: 0.80 },
      { domain: 'ards', subtype: 'inhalation', baseSeverity: 0.65 },
    ],
    initialVitals: { heartRate: 118, systolicBP: 102, diastolicBP: 65, meanArterialPressure: 77, spo2: 91, paCO2: 44, pH: 7.28, lactate: 4.2 },
    isVentilatorConnected: true,
    ventilatorPreset: { fio2: 1.0, peep: 8 },
    clinicalNotes: 'FiO₂ 1.0 hasta SpCO < 5% (vida media CO: 5h AA → 60min FiO₂ 1.0). HBOT si posible. Broncoscopia BAL temprano.',
    references: ['Weaver LK NEJM 2002', 'Dries DJ J Burn Care Res 2013'],
  },
  {
    id: 'crush_with_rhabdo',
    category: 'trauma',
    name: 'Síndrome de Aplastamiento — Rhabdo + Síndrome Compartimental',
    description: 'Paciente atrapado 8h bajo escombros. Síndrome de aplastamiento bilateral MMII. CPK 240000. AKI estadio 2. Síndrome compartimental inminente.',
    baseSeverity: 0.82,
    tags: ['Aplastamiento', 'Rabdomiólisis', 'Síndrome Compartimental', 'Fasciotomía'],
    pathologyConfigs: [
      { domain: 'polytrauma', subtype: 'crush', baseSeverity: 0.80 },
    ],
    initialVitals: { heartRate: 116, systolicBP: 88, diastolicBP: 55, meanArterialPressure: 66, lactate: 3.8, urineOutput: 0.12, creatinine: 4.2 },
    isVentilatorConnected: false,
    clinicalNotes: 'SF 1-1.5 L/h → diuresis 200-300 mL/h. Alcalinización orina. Fasciotomía doble incisión si presión > 30 mmHg o Δ < 30 mmHg.',
    references: ['Better OS JASN 1992', 'Bosch X AIM 2009'],
  },
  {
    id: 'tbi_torax_combined',
    category: 'trauma',
    name: 'Politrauma: TCE + Tórax — Manejo Dual',
    description: 'TCE moderado (GCS 9) + hemotórax derecho + fractura costal múltiple (flail chest). ARM requerida por tórax inestable + protección cerebral.',
    baseSeverity: 0.78,
    tags: ['TCE', 'Tórax', 'Flail Chest', 'ARM', 'Politrauma'],
    pathologyConfigs: [
      { domain: 'neuroCritical', subtype: 'tbi', baseSeverity: 0.65 },
      { domain: 'polytrauma', subtype: null, baseSeverity: 0.72 },
    ],
    initialVitals: { heartRate: 108, systolicBP: 108, diastolicBP: 68, meanArterialPressure: 81, gcs: 9, spo2: 88, lactate: 3.4 },
    isVentilatorConnected: true,
    ventilatorPreset: { fio2: 0.60, peep: 6, vt: 440 },
    clinicalNotes: 'Pleurostomía tubo hemotórax. ARM: VT 6-8 mL/kg PBW, PEEP mínimo para oxigenar (PPC > 60). Meta pCO₂ 35-40 mmHg.',
    references: ['Bulger EM J Trauma 2000', 'ATLS 10th ed 2018'],
  },
];
