// src/scenarios/cardiac/index.ts — 9 cardiac scenarios
import type { ScenarioDefinition } from '../../store/useScenarioStore';

export const cardiacExtScenarios: ScenarioDefinition[] = [
  {
    id: 'stemi_cardiogenic_shock',
    category: 'cardio',
    name: 'STEMI + Shock Cardiogénico',
    description: 'IAM anterior extenso (KILLIP IV). Inicio hace 3h, sin reperfusión aún. FC 118, PA 72/45, IC 1.4 L/min/m², PCWP 26. Balón de contrapulsación indicado.',
    baseSeverity: 0.88,
    tags: ['STEMI', 'Shock', 'Cardiogénico', 'IAM', 'IABP'],
    pathologyConfigs: [
      { domain: 'cardio', subtype: 'stemi_shock', baseSeverity: 0.88 },
    ],
    initialVitals: { heartRate: 118, systolicBP: 72, diastolicBP: 45, meanArterialPressure: 54, cardiacOutput: 2.5, spo2: 88, lactate: 5.2, urineOutput: 0.2 },
    isVentilatorConnected: true,
    ventilatorPreset: { fio2: 0.70, peep: 8 },
    clinicalNotes: 'Dobutamina 5-10 mcg/kg/min. Noradrenalina si MAP < 65. Hemodiálisis si AKI. Coronarografía urgente < 2h.',
    references: ['Thiele H NEJM 2017 (CULPRIT-SHOCK)', 'Mebazaa A Eur Heart J 2018'],
  },
  {
    id: 'acute_heart_failure_cpe',
    category: 'cardio',
    name: 'IC Aguda — EAP Hipoxémico',
    description: 'Edema agudo de pulmón en paciente con IC avanzada (FEVI 20%). SpO₂ 82% en AA. Disnea severa, crepitantes bilaterales hasta ápices, PAS 185 mmHg.',
    baseSeverity: 0.72,
    tags: ['ICC', 'EAP', 'IC Aguda', 'HFNC', 'BiPAP'],
    pathologyConfigs: [
      { domain: 'cardio', subtype: 'hf_decompensated', baseSeverity: 0.72 },
      { domain: 'ards', subtype: null, baseSeverity: 0.45 },
    ],
    initialVitals: { heartRate: 108, systolicBP: 185, diastolicBP: 110, meanArterialPressure: 135, spo2: 82, respiratoryRate: 36, lactate: 2.8 },
    isVentilatorConnected: false,
    recommendedRespSupport: 'hfnc',
    clinicalNotes: 'CPAP 10 cmH₂O o BiPAP. Furosemida IV 80mg. NTG sublingual → NTG IV. Monitoreo invasivo si no responde. Evitar intubación si posible.',
    references: ['Ponikowski P ESC HF Guidelines 2021', 'Mebazaa A Intensive Care Med 2015 (ALARM-HF)'],
  },
  {
    id: 'tamponade',
    category: 'cardio',
    name: 'Taponamiento Cardíaco',
    description: 'Derrame pericárdico masivo (efecto tamponade) en contexto de pericarditis viral. Tríada de Beck. PAS 70 mmHg con pulso paradojal 22 mmHg. Urgencia drenaje.',
    baseSeverity: 0.90,
    tags: ['Taponamiento', 'Pericarditis', 'Drenaje', 'Urgencia'],
    pathologyConfigs: [
      { domain: 'cardio', subtype: 'tamponade', baseSeverity: 0.90 },
    ],
    initialVitals: { heartRate: 132, systolicBP: 70, diastolicBP: 50, meanArterialPressure: 57, spo2: 94, lactate: 4.8 },
    isVentilatorConnected: false,
    clinicalNotes: 'Pericardiocentesis urgente guiada por ecocardiograma. Volumen IV para mantener precarga. Evitar vasodilatadores. No ventilación con presión positiva si posible.',
    references: ['Spodick DH NEJM 2003', 'Adler Y ESC Pericarditis 2015'],
  },
  {
    id: 'massive_pe',
    category: 'cardio',
    name: 'TEP Masivo — Shock Obstructivo',
    description: 'TEP masivo con colapso hemodinámico. TAS 65 mmHg, taquicardia sinusal 130 bpm. Angio-TC confirmado. Trombo en silla de montar. Decisión trombolisis vs embolectomía.',
    baseSeverity: 0.92,
    tags: ['TEP', 'Tromboembolismo', 'Shock', 'Trombolisis', 'ARM'],
    pathologyConfigs: [
      { domain: 'cardio', subtype: 'massive_pe', baseSeverity: 0.92 },
      { domain: 'ards', subtype: null, baseSeverity: 0.40 },
    ],
    initialVitals: { heartRate: 130, systolicBP: 65, diastolicBP: 40, meanArterialPressure: 48, spo2: 85, lactate: 4.2, cardiacOutput: 2.8 },
    isVentilatorConnected: true,
    ventilatorPreset: { fio2: 0.80, peep: 6 },
    clinicalNotes: 'Alteplase 100mg/2h si no hay contraindicación. Heparina IV post-trombolisis 12h. Soporte hemodinámico: noradrenalina + dobutamina. Embolectomía quirúrgica como rescate.',
    references: ['Konstantinides SV ESC PE Guidelines 2019', 'Meyer G NEJM 2014 (PEITHO)'],
  },
  {
    id: 'post_cabg_low_output',
    category: 'cardio',
    name: 'Post-CABG — Síndrome de Bajo Gasto',
    description: 'Post-revascularización quirúrgica x4 vasos. Extubación fallida. IC 1.8 L/min/m². PCWP 24 mmHg. Necesita inotrópicos + diuréticos.',
    baseSeverity: 0.70,
    tags: ['Post-CABG', 'Bajo Gasto', 'Inotrópicos', 'PiCCO'],
    pathologyConfigs: [
      { domain: 'cardio', subtype: 'post_cardiac_surgery', baseSeverity: 0.70 },
    ],
    initialVitals: { heartRate: 88, systolicBP: 95, diastolicBP: 60, meanArterialPressure: 72, cardiacOutput: 3.2, lactate: 2.6, urineOutput: 0.35 },
    isVentilatorConnected: true,
    clinicalNotes: 'Dobutamina 5 mcg/kg/min. Furosemida IV. Monitoreo CO con PiCCO o Swan-Ganz. Meta: IC > 2.2, PCWP < 18.',
    references: ['Mehta RH JAMA 2006', 'Lomivorotov VV J Cardiothorac Vasc Anesth 2017'],
  },
  {
    id: 'aortic_dissection_type_a',
    category: 'cardio',
    name: 'Disección Aórtica Tipo A',
    description: 'Disección tipo A de Stanford. Dolor desgarrador que irradia a espalda. PA diferencial entre brazos. TC confirmado. Quirúrgico urgente.',
    baseSeverity: 0.94,
    tags: ['Disección', 'Aorta', 'Cirugía Urgente', 'Antihipertensivo'],
    pathologyConfigs: [
      { domain: 'cardio', subtype: 'aortic_dissection', baseSeverity: 0.94 },
    ],
    initialVitals: { heartRate: 116, systolicBP: 175, diastolicBP: 95, meanArterialPressure: 122, spo2: 95, lactate: 2.0 },
    isVentilatorConnected: false,
    clinicalNotes: 'Labetalol IV → SBP 100-120 mmHg. FC < 60 bpm. NO fibrinolíticos. Quirúrgico urgente: reemplaza aorta ascendente.',
    references: ['Erbel R ESC Aortic Diseases 2014', 'Hiratzka LF ACC/AHA 2010'],
  },
  {
    id: 'refractory_vt_storm',
    category: 'cardio',
    name: 'Tormenta de TV Refractaria',
    description: 'Tormenta eléctrica (> 3 episodios TV sostenida/24h) en miocardiopatía isquémica. Múltiples cardioversiones fallidas. Sedación profunda y amiodarona en curso.',
    baseSeverity: 0.84,
    tags: ['TV', 'Tormenta Eléctrica', 'Amiodarona', 'Ablación', 'ARM'],
    pathologyConfigs: [
      { domain: 'cardio', subtype: 'vt_storm', baseSeverity: 0.84 },
    ],
    initialVitals: { heartRate: 168, systolicBP: 82, diastolicBP: 52, meanArterialPressure: 62, spo2: 92, lactate: 3.2 },
    isVentilatorConnected: true,
    clinicalNotes: 'Amiodarona 300mg IV → infusión 1 mg/min. Sedoanalgesia: propofol + fentanil. Lidocaína IV alternativa. Ablación transcatéter electiva.',
    references: ['Priori SG ESC VA/VT 2015', 'Connolly SJ NEJM 2006 (SCD-HeFT)'],
  },
  {
    id: 'nstemi_with_pe',
    category: 'cardio',
    name: 'NSTEMI + TEP Submasivo',
    description: 'NSTEMI de alto riesgo (TIMI 6) con TEP submasivo concomitante (RV disfunción, BNP 2800). Dilema terapéutico: anticoagulación plena vs ICP urgente.',
    baseSeverity: 0.76,
    tags: ['NSTEMI', 'TEP Submasivo', 'HBPM', 'ICP'],
    pathologyConfigs: [
      { domain: 'cardio', subtype: 'nstemi', baseSeverity: 0.70 },
    ],
    initialVitals: { heartRate: 108, systolicBP: 100, diastolicBP: 62, meanArterialPressure: 75, spo2: 91, lactate: 2.4 },
    isVentilatorConnected: false,
    clinicalNotes: 'Anticoagulación con HNF. ICP temprana (< 24h) si isquemia persistente. Ecocardio urgente. Monitoreo PA invasiva.',
    references: ['Collet JP ESC NSTEMI 2020', 'Amsterdam EA ACC/AHA NSTEMI 2014'],
  },
  {
    id: 'post_aortic_valve_replacement',
    category: 'cardio',
    name: 'Post-TAVI — Bloqueo AV Completo',
    description: 'Post-implante válvula aórtica transcatéter (TAVI). Bloqueo AV completo de nuevo inicio. Ritmo de escape juncional 38 bpm. Hemodinámicamente comprometido.',
    baseSeverity: 0.65,
    tags: ['TAVI', 'BAV Completo', 'Marcapasos', 'Post-Procedimiento'],
    pathologyConfigs: [
      { domain: 'cardio', subtype: 'post_tavi', baseSeverity: 0.65 },
    ],
    initialVitals: { heartRate: 38, systolicBP: 78, diastolicBP: 48, meanArterialPressure: 58, spo2: 95, lactate: 1.8 },
    isVentilatorConnected: false,
    clinicalNotes: 'Marcapasos transvenoso temporal urgente. Electrolitos (hiperkalemia). Si persiste > 48h: evaluar marcapasos definitivo (DDDR). Corticoides si edema.',
    references: ['Popma JJ NEJM 2019', 'Regueiro A JAMA 2016'],
  },
];
