// src/scenarios/respiratory/index.ts — 9 respiratory scenarios
import type { ScenarioDefinition } from '../../store/useScenarioStore';

export const respiratoryExtScenarios: ScenarioDefinition[] = [
  {
    id: 'ards_severe_pneumonia_ext',
    category: 'respiratory',
    name: 'SDRA Severo — Neumonía Bilateral',
    description: 'SDRA grave (P/F 72, Berlin). Neumonía bilateral por Legionella. Decúbito prono indicado. SpO₂ 86% con FiO₂ 0.85 + PEEP 14.',
    baseSeverity: 0.90,
    tags: ['SDRA', 'Prono', 'Legionella', 'ARM', 'Berlin'],
    pathologyConfigs: [
      { domain: 'ards', subtype: null, baseSeverity: 0.90 },
      { domain: 'pneumonia', subtype: 'atipica', baseSeverity: 0.80 },
    ],
    initialVitals: { heartRate: 122, systolicBP: 88, diastolicBP: 55, meanArterialPressure: 66, spo2: 86, paO2: 62, paCO2: 48, pfRatio: 72, ardsActive: true, ardsSeverityLevel: 'SEVERE', lactate: 3.2 },
    isVentilatorConnected: true,
    ventilatorPreset: { fio2: 0.85, peep: 14, vt: 320, setRR: 22 },
    clinicalNotes: 'Prono 16h/d (Guérin NEJM 2013). NMBA cisatracurio primeras 48h. Azitromicina + betalactámico. Meta: P/F > 150 para desescalar PEEP.',
    references: ['Guérin C NEJM 2013 (PROSEVA)', 'Fan E JAMA 2017'],
  },
  {
    id: 'ards_aspiration',
    category: 'respiratory',
    name: 'SDRA por Aspiración — Neumonitis Química',
    description: 'Aspiración masiva de contenido gástrico post-intubación emergencia. SDRA moderado de instalación rápida (P/F 118). Broncoespasmo.',
    baseSeverity: 0.74,
    tags: ['Aspiración', 'SDRA', 'ARM', 'Broncoespasmo'],
    pathologyConfigs: [
      { domain: 'ards', subtype: 'aspiration', baseSeverity: 0.74 },
      { domain: 'pneumonia', subtype: 'quimica', baseSeverity: 0.60 },
    ],
    initialVitals: { heartRate: 118, systolicBP: 98, diastolicBP: 62, meanArterialPressure: 74, spo2: 88, pfRatio: 118, ardsActive: true, ardsSeverityLevel: 'MODERATE' },
    isVentilatorConnected: true,
    ventilatorPreset: { fio2: 0.70, peep: 10, vt: 380 },
    clinicalNotes: 'Broncoaspiración lavado. Broncodilatadores. Corticoides NO indicados rutinariamente. Antibiótico si aspiración contaminada.',
    references: ['Raghavendran K Crit Care 2011', 'Marik PE Intensive Care Med 2011'],
  },
  {
    id: 'copd_exacerbation_severe',
    category: 'respiratory',
    name: 'EPOC Agudizado Severo — VMNI',
    description: 'EPOC GOLD III agudizado (infección viral). pH 7.25, pCO₂ 72 mmHg. BiPAP indicado. Riesgo intubación si falla VMNI en 2h.',
    baseSeverity: 0.68,
    tags: ['EPOC', 'Exacerbación', 'BiPAP', 'VMNI', 'Hipercapnia'],
    pathologyConfigs: [
      { domain: 'copd', subtype: null, baseSeverity: 0.68 },
    ],
    initialVitals: { heartRate: 112, systolicBP: 155, diastolicBP: 88, meanArterialPressure: 110, spo2: 86, paO2: 52, paCO2: 72, pH: 7.25, hco3: 31, respiratoryRate: 32 },
    isVentilatorConnected: false,
    recommendedRespSupport: 'hfnc',
    clinicalNotes: 'BiPAP IPAP 18/EPAP 6. O₂ titulado SpO₂ 88-92%. Broncodilatadores + metilprednisolona 40mg. Antibiótico si esputo purulento.',
    references: ['Brochard L NEJM 1995', 'GOLD 2024 Report'],
  },
  {
    id: 'asthma_status',
    category: 'respiratory',
    name: 'Estado Asmático Refractario',
    description: 'Estado asmático severo sin respuesta a broncodilatadores × 2h. Peak flow < 25% teórico. Silencio auscultatorio bilateral. Ketamina indicada.',
    baseSeverity: 0.82,
    tags: ['Asma', 'Estado Asmático', 'Ketamina', 'ARM', 'Broncoespasmo Severo'],
    pathologyConfigs: [
      { domain: 'asthma', subtype: 'status_asthmaticus', baseSeverity: 0.82 },
    ],
    initialVitals: { heartRate: 138, systolicBP: 108, diastolicBP: 68, meanArterialPressure: 81, spo2: 88, paCO2: 52, pH: 7.28, respiratoryRate: 38 },
    isVentilatorConnected: true,
    ventilatorPreset: { fio2: 0.80, peep: 4, vt: 350, setRR: 12 },
    clinicalNotes: 'Ketamina 1-2 mg/kg IV anestesia disociativa. Salbutamol neb continuo. Magnesio 2g IV. Permissive hypercapnia. Evitar auto-PEEP.',
    references: ['Fernández A Rev Esp Anestesiol 2015', 'GINA 2024'],
  },
  {
    id: 'pneumothorax_tension',
    category: 'respiratory',
    name: 'Neumotórax a Tensión',
    description: 'Neumotórax a tensión en paciente ventilado mecánicamente. PIP sube abruptamente. SpO₂ cae. Desviación traqueal izquierda. Diagnóstico clínico — no esperar Rx.',
    baseSeverity: 0.88,
    tags: ['Neumotórax', 'Tensión', 'ARM', 'Emergencia'],
    pathologyConfigs: [
      { domain: 'ards', subtype: 'pneumothorax', baseSeverity: 0.80 },
    ],
    initialVitals: { heartRate: 142, systolicBP: 68, diastolicBP: 40, meanArterialPressure: 49, spo2: 78, lactate: 4.0 },
    isVentilatorConnected: true,
    ventilatorPreset: { fio2: 1.0, peep: 6 },
    clinicalNotes: 'Descompresión con aguja 2° EIC línea mediaclavicular INMEDIATA. Luego pleurostomía tubo. No demorar por imagen.',
    references: ['Leigh-Smith S BJM 2003', 'ATLS 10th ed 2018'],
  },
  {
    id: 'covid_severe_ecmo',
    category: 'respiratory',
    name: 'COVID-19 SDRA Severo — Candidato ECMO',
    description: 'COVID-19 con SDRA grave (P/F 58) refractario a prono × 3 ciclos y reclutamiento alveolar máximo. Candidato ECMO venovenoso.',
    baseSeverity: 0.92,
    tags: ['COVID', 'SDRA', 'ECMO', 'ARM', 'Prono'],
    pathologyConfigs: [
      { domain: 'ards', subtype: 'covid', baseSeverity: 0.92 },
      { domain: 'sepsis', subtype: null, baseSeverity: 0.45 },
    ],
    initialVitals: { heartRate: 128, systolicBP: 82, diastolicBP: 52, meanArterialPressure: 62, spo2: 82, pfRatio: 58, ardsActive: true, ardsSeverityLevel: 'SEVERE', lactate: 2.8 },
    isVentilatorConnected: true,
    ventilatorPreset: { fio2: 1.0, peep: 16, vt: 280 },
    clinicalNotes: 'Dexametasona 6mg/d (RECOVERY). Baricitinib si fenotipo hiperinflamatorio. Cánula ECMO VV: 23-25 Fr femoral + 19-21 Fr yugular.',
    references: ['RECOVERY Lancet 2021', 'Combes A JAMA 2018 (EOLIA)', 'Grotberg JC Crit Care 2023'],
  },
  {
    id: 'pulmonary_hemorrhage',
    category: 'respiratory',
    name: 'Hemorragia Pulmonar Difusa',
    description: 'Hemorragia alveolar difusa (HAD) en paciente con LES activo. Hemoptisis masiva, PaO₂ 52 mmHg. ANCA (+). Lavado broncoalveolar sanguinolento.',
    baseSeverity: 0.85,
    tags: ['HAD', 'Hemorragia Alveolar', 'LES', 'ANCA', 'ARM'],
    pathologyConfigs: [
      { domain: 'ards', subtype: 'hemorrhage', baseSeverity: 0.85 },
    ],
    initialVitals: { heartRate: 118, systolicBP: 102, diastolicBP: 65, meanArterialPressure: 77, spo2: 84, pfRatio: 98, ardsActive: true, ardsSeverityLevel: 'SEVERE' },
    isVentilatorConnected: true,
    ventilatorPreset: { fio2: 0.90, peep: 12 },
    clinicalNotes: 'Metilprednisolona 1g/d × 3d. Rituximab o plasmaféresis si ANCA (+). Vasopresina tópica (broncoscopia). Evitar anticoagulación.',
    references: ['Lara AR Crit Care Med 2008', 'Cartin-Ceba R Rheum Dis Clin 2010'],
  },
  {
    id: 'pe_submassive',
    category: 'respiratory',
    name: 'TEP Submasivo — RV Strain',
    description: 'TEP submasivo con disfunción RV confirmada (eco). BNP 1800, Troponina (+). Hemodinámica preservada por ahora. Decisión trombolisis vs anticoagulación plena.',
    baseSeverity: 0.68,
    tags: ['TEP', 'Submasivo', 'RV', 'Anticoagulación'],
    pathologyConfigs: [
      { domain: 'cardio', subtype: 'pe_submassive', baseSeverity: 0.68 },
    ],
    initialVitals: { heartRate: 108, systolicBP: 108, diastolicBP: 68, meanArterialPressure: 81, spo2: 92, lactate: 1.8 },
    isVentilatorConnected: false,
    clinicalNotes: 'HNF bolo + infusión. Monitoreo estrecho PA y SaO₂. Ecocardio seriado. Trombolisis si deterioro (PESI alto + RV disfunción + Tn+).',
    references: ['Goldaber MK JAMA 2012', 'ESC TEP 2019'],
  },
  {
    id: 'pleural_empyema',
    category: 'respiratory',
    name: 'Empiema Pleural — Sepsis Secundaria',
    description: 'Empiema pleural loculado derecho complicando neumonía bacteriana. Sepsis leve. Fiebre persistente × 10d pese a antibióticos. Necesita drenaje quirúrgico o VATS.',
    baseSeverity: 0.62,
    tags: ['Empiema', 'Pleural', 'Sepsis', 'Drenaje', 'VATS'],
    pathologyConfigs: [
      { domain: 'sepsis', subtype: null, baseSeverity: 0.55 },
      { domain: 'pneumonia', subtype: 'bacteriana', baseSeverity: 0.60 },
    ],
    initialVitals: { heartRate: 102, systolicBP: 118, diastolicBP: 72, meanArterialPressure: 87, spo2: 94, temperature: 39.2, lactate: 2.0 },
    isVentilatorConnected: false,
    clinicalNotes: 'Ecografía pleural: loculación? Drenaje percutáneo + alteplasa intrapleural (MIST2). Si falla → VATS decortication. ATB ajustado cultivo líquido.',
    references: ['Rahman NM NEJM 2011 (MIST2)', 'Light RW Am Rev Respir Dis 1972'],
  },
];
