import type { ScenarioDefinition } from '../store/useScenarioStore';

// Fórmula Parkland: 4 mL × peso(kg) × TBSA(%) en 24h (½ primeras 8h)
// Referencias: Baxter CR 1968; ABA Guidelines 2022; American Burn Association
// Peso estándar: 75 kg (ajustar en applyScenario si peso conocido)
// Nota: para 40% TBSA, 75 kg → 4×75×40 = 12.000 mL/24h (500 mL/h primeras 8h)

export const burnScenarios: ScenarioDefinition[] = [
  {
    id: 'burn_fuego_40pct',
    category: 'burns',
    name: 'Quemadura 40% TBSA — Fuego',
    description: 'Quemadura por llama en accidente doméstico. 40% TBSA: 25% profundo parcial + 15% espesor total. Cara, tronco y miembros superiores. Vía aérea comprometida: quemadura facial + estridor.',
    baseSeverity: 0.82,
    tags: ['40% TBSA', 'Vía aérea', 'Parkland', 'Escharotomía', 'Inhalación'],
    pathologyConfigs: [
      { domain: 'burn',             subtype: 'fuego',  baseSeverity: 0.82 },
      { domain: 'ards',             subtype: null,     baseSeverity: 0.45 },
      { domain: 'hemorrhagicShock', subtype: '2',      baseSeverity: 0.35 },
    ],
    initialVitals: {
      heartRate: 128,
      systolicBP: 92,
      diastolicBP: 56,
      meanArterialPressure: 68,
      cardiacOutput: 6.8,
      strokeVolume: 53,
      svr: 935,
      cvp: 4,
      spo2: 93,
      respiratoryRate: 26,
      paO2: 72,
      paCO2: 37,
      pfRatio: 240,
      ardsActive: true,
      ardsSeverityLevel: 'MILD',
      icp: 12,
      gcs: 13,
      pupilState: 'reactive',
      lactate: 3.0,
      pH: 7.32,
      hco3: 20.5,
      baseExcess: -4.8,
      temperature: 38.5,
      urineOutput: 0.5,
      creatinine: 1.2,
    },
    isVentilatorConnected: true,
    ventilatorPreset: {
      mode: 'VC-AC',
      fio2: 0.60,
      vt: 450,
      peep: 8,
      setRR: 18,
    },
    initialBloodVolumeMl: 4200,
    clinicalNotes: 'Intubación de secuencia rápida PRECOZ si quemadura facial/estridor (edema progresivo hace intubación imposible a 6–12h). Parkland: 4 mL×kg×%TBSA; primeras 8h = 50%, siguientes 16h = 50%. Objetivo diuresis 0.5–1 mL/kg/h (adultó) como guía de resucitación. Escharotomía si síndrome compartimental circular. CO-oximetría (SpO₂ puede ser falsamente normal con intox CO).',
    references: ['Baxter CR Surg Clin N Am 1968', 'Pham TN ABA 2008', 'Greenhalgh DG J Burn Care 2019'],
  },

  {
    id: 'burn_electrico_alto_voltaje',
    category: 'burns',
    name: 'Quemadura Eléctrica — Alto Voltaje + Rabdomiólisis',
    description: 'Electrocución 25.000 V industrial. Puntos de entrada/salida en mano y pie izquierdos. TBSA cutáneo aparente 8% pero lesión de partes blandas profundas extensas. Orina color oscuro.',
    baseSeverity: 0.78,
    tags: ['Eléctrica', 'Rabdomiólisis', 'CK', 'Mioglobina', 'Fasciotomía'],
    pathologyConfigs: [
      { domain: 'burn',             subtype: 'electrico', baseSeverity: 0.78 },
      { domain: 'hemorrhagicShock', subtype: '2',         baseSeverity: 0.30 },
    ],
    initialVitals: {
      heartRate: 108,
      systolicBP: 105,
      diastolicBP: 65,
      meanArterialPressure: 78,
      cardiacOutput: 5.8,
      strokeVolume: 54,
      svr: 1195,
      cvp: 6,
      spo2: 97,
      respiratoryRate: 18,
      paO2: 90,
      paCO2: 38,
      pfRatio: 429,
      ardsActive: false,
      ardsSeverityLevel: 'NONE',
      icp: 12,
      gcs: 13,
      pupilState: 'reactive',
      lactate: 4.2,
      pH: 7.28,
      hco3: 19.5,
      baseExcess: -6.2,
      temperature: 37.8,
      urineOutput: 0.2,
      creatinine: 2.2,
    },
    isVentilatorConnected: false,
    recommendedRespSupport: 'nasal_cannula',
    initialBloodVolumeMl: 4500,
    clinicalNotes: 'Forzar diuresis 1–2 mL/kg/h hasta aclaramiento mioglobinuria (orina clara). Bicarbonato IV para alcalinizar orina (reduce precipitación tubular de mioglobina, objetivo pH orina > 6.5). ECG seriados (arritmias tardías). Fasciotomía urgente si compartimento muscular en tensión. CK > 5000 UI/L → monitorizar AKI. TBSA subestima la lesión real.',
    references: ['Koumbourlis AC 2002 Paediatric', 'Arnoldo BD J Burn Care 2004', 'ABA Guidelines'],
  },

  {
    id: 'burn_explosion_blast',
    category: 'burns',
    name: 'Explosión + Blast Injury',
    description: 'Explosión de gas doméstico. Blast primario (barotrauma pulmonar) + quemaduras 30% TBSA + trauma contuso abdominal. Hemotórax bilateral.',
    baseSeverity: 0.85,
    tags: ['Blast', 'Barotrauma', 'Explosión', 'Hemotórax', 'Politrauma'],
    pathologyConfigs: [
      { domain: 'burn',             subtype: 'explosion', baseSeverity: 0.85 },
      { domain: 'ards',             subtype: null,        baseSeverity: 0.65 },
      { domain: 'hemorrhagicShock', subtype: '2',         baseSeverity: 0.55 },
    ],
    initialVitals: {
      heartRate: 135,
      systolicBP: 88,
      diastolicBP: 52,
      meanArterialPressure: 64,
      cardiacOutput: 6.5,
      strokeVolume: 48,
      svr: 882,
      cvp: 3,
      spo2: 88,
      respiratoryRate: 32,
      paO2: 58,
      paCO2: 40,
      pfRatio: 145,
      ardsActive: true,
      ardsSeverityLevel: 'SEVERE',
      icp: 12,
      gcs: 12,
      pupilState: 'reactive',
      lactate: 5.8,
      pH: 7.24,
      hco3: 17.0,
      baseExcess: -9.5,
      temperature: 36.2,
      urineOutput: 0.3,
      creatinine: 1.5,
    },
    isVentilatorConnected: true,
    ventilatorPreset: {
      mode: 'VC-AC',
      fio2: 0.75,
      vt: 400,
      peep: 10,
      setRR: 20,
    },
    initialBloodVolumeMl: 3800,
    clinicalNotes: 'Blast pulmonar: SDRA de inicio precoz (primeras 24h). Usar VT bajos (4–6 mL/kg). ¡CUIDADO con neumotórax a tensión en ventilación mecánica! Drenaje hemotórax bilateral urgente. Evaluación sistémica: lesión intestinal por blast (perforación tardía), trauma ocular (ruptura globo ocular). Quemaduras sobre blast: peor pronóstico que cada lesión por separado.',
    references: ['DePalma RG NEJM 2005', 'Wightman JM Prehospital Emerg Care 2001', 'ABA Guidelines 2022'],
  },

  {
    id: 'burn_quimico_ocular_via_aerea',
    category: 'burns',
    name: 'Quemadura Química — Ocular + Vía Aérea',
    description: 'Exposición a ácido sulfúrico concentrado. Quemaduras faciales y oculares bilaterales grado III. Quemadura de vía aérea superior confirmada por broncoscopia. 20% TBSA cara/cuello.',
    baseSeverity: 0.75,
    tags: ['Ácido', 'Quemadura ocular', 'Vía aérea', 'Decontaminación', 'Broncoscopia'],
    pathologyConfigs: [
      { domain: 'burn', subtype: 'quimico', baseSeverity: 0.75 },
      { domain: 'ards', subtype: null,      baseSeverity: 0.40 },
    ],
    initialVitals: {
      heartRate: 118,
      systolicBP: 108,
      diastolicBP: 68,
      meanArterialPressure: 81,
      cardiacOutput: 6.2,
      strokeVolume: 53,
      svr: 1175,
      cvp: 7,
      spo2: 91,
      respiratoryRate: 24,
      paO2: 70,
      paCO2: 38,
      pfRatio: 233,
      ardsActive: true,
      ardsSeverityLevel: 'MILD',
      icp: 12,
      gcs: 14,
      pupilState: 'reactive',
      lactate: 2.5,
      pH: 7.34,
      hco3: 21.5,
      baseExcess: -3.2,
      temperature: 37.5,
      urineOutput: 0.6,
      creatinine: 1.0,
    },
    isVentilatorConnected: true,
    ventilatorPreset: {
      mode: 'VC-AC',
      fio2: 0.55,
      vt: 450,
      peep: 8,
      setRR: 18,
    },
    clinicalNotes: 'Decontaminación: agua abundante 30 min (ácidos y álcalis). NO neutralizar (genera calor exotérmico). Colirio de irrigación ocular continuo (NaCl 0.9%) hasta pH lagrimal normalizado. Intubación precoz: edema laríngeo progresivo. Broncoscopia terapéutica para eliminar tapones mucosos y coágulos. Consulta urgente oftalmología para quemaduras > grado II (riesgo ceguera).',
    references: ['Merle H J Fr Ophtalmol 2005', 'Sheridan RL Burns 2010', 'Kuckelkorn R Ophthalmologe 2002'],
  },
];
