import type { ScenarioDefinition } from '../store/useScenarioStore';

// Referencias: AHA/ACC 2013 (STEMI); van Diepen S AHA 2017 (shock cardiogénico);
//              ESC TEP 2019 (Konstantinides); AHA/ACC 2022 (disección aorta);
//              Siu CW CCM 2009 (diltiazem vs amio FA); Bosch NA Chest 2020 (β-bloq vs amio vs dig)

export const cardioScenarios: ScenarioDefinition[] = [
  {
    id: 'cardio_iam_stemi_anterior_shock',
    category: 'cardio',
    name: 'IAM STEMI Anterior + Shock Cardiogénico',
    description: 'IAM anterior extenso por oclusión proximal de DA. Killip IV. Shock cardiogénico post-isquémico. FE estimada 20%. Edema agudo de pulmón. ACTP primaria pendiente.',
    baseSeverity: 0.88,
    tags: ['IAM', 'STEMI', 'Killip IV', 'Dobutamina', 'IABCP'],
    pathologyConfigs: [
      { domain: 'cardio',    subtype: 'iam_stemi_anterior',  baseSeverity: 0.88 },
      { domain: 'ards',      subtype: null,                   baseSeverity: 0.55 },
      { domain: 'sepsis',    subtype: null,                   baseSeverity: 0.10 },
    ],
    initialVitals: {
      heartRate: 110,
      systolicBP: 82,
      diastolicBP: 55,
      meanArterialPressure: 64,
      cardiacOutput: 2.8,
      strokeVolume: 25,
      svr: 1725,
      cvp: 18,
      spo2: 90,
      respiratoryRate: 30,
      paO2: 62,
      paCO2: 32,
      pfRatio: 207,
      ardsActive: true,
      ardsSeverityLevel: 'MODERATE',
      icp: 12,
      gcs: 13,
      pupilState: 'reactive',
      lactate: 3.8,
      pH: 7.32,
      hco3: 20.0,
      baseExcess: -5.5,
      temperature: 36.8,
      urineOutput: 0.2,
      creatinine: 1.8,
    },
    isVentilatorConnected: true,
    ventilatorPreset: {
      mode: 'VC-AC',
      fio2: 0.60,
      vt: 420,
      peep: 8,
      setRR: 18,
    },
    initialModifiers: {
      svrMultiplier: 1.35,
      capillaryLeakRate: 2.5,
      hyperdynamicFactor: 0.95,
      lungShuntFraction: 0.38,
      complianceMultiplier: 0.62,
    },
    clinicalNotes: 'Shock cardiogénico: mortalidad 40–50%. Soporte hemodinámico precoz: dobutamina 2–20 mcg/kg/min + noradrenalina si MAP < 65. IABCP no redujo mortalidad en IABP-SHOCK II (NEJM 2012). ACTP primaria reduce mortalidad incluso en shock. Impella o ECMO-VA en shock refractario (centros especializados). Evitar betabloqueantes agudos.',
    references: ['van Diepen S AHA Circ 2017', 'Thiele H IABP-SHOCK II NEJM 2012', 'Hochman JS JAMA 2006'],
  },

  {
    id: 'cardio_iam_inferior_bav',
    category: 'cardio',
    name: 'IAM Inferior + BAV Completo',
    description: 'IAM inferior-posterior por oclusión de CD proximal. Bradicardia severa por BAV completo (bloqueo infranodal). FC 38 lpm. Hipotensión. ST elevado en II, III, aVF + depresión especular.',
    baseSeverity: 0.72,
    tags: ['IAM inferior', 'BAV III', 'Marcapasos', 'Atropina', 'ACTP'],
    pathologyConfigs: [
      { domain: 'cardio',    subtype: 'iam_stemi_inferior', baseSeverity: 0.72 },
      { domain: 'sepsis',    subtype: null,                  baseSeverity: 0.05 },
    ],
    initialVitals: {
      heartRate: 38,
      systolicBP: 88,
      diastolicBP: 58,
      meanArterialPressure: 68,
      cardiacOutput: 2.5,
      strokeVolume: 66,
      svr: 2112,
      cvp: 14,
      spo2: 93,
      respiratoryRate: 22,
      paO2: 80,
      paCO2: 38,
      pfRatio: 381,
      ardsActive: false,
      ardsSeverityLevel: 'NONE',
      icp: 12,
      gcs: 14,
      pupilState: 'reactive',
      lactate: 2.5,
      pH: 7.33,
      hco3: 21.0,
      baseExcess: -4.2,
      temperature: 36.5,
      urineOutput: 0.4,
      creatinine: 1.3,
    },
    isVentilatorConnected: false,
    recommendedRespSupport: 'nasal_cannula',
    clinicalNotes: 'BAV 3° en IAM inferior: generalmente supranodal (nodal), reversible con reperfusión. Atropina 0.5 mg puede ser útil (BAV nodal responde; infranodal no). Marcapasos transcutáneo si bradicardia sintomática; transvenoso en sala cath. ACTP primaria es el tratamiento definitivo. Evitar reperfusión sin control del BAV (reperfusión puede acelerar BAV transitoriamente). VD depresión frecuente → cuidado con nitratos y diuréticos.',
    references: ['ACC/AHA STEMI Guidelines 2013', 'Epstein AE AHA 2008', 'Zeymer U EHJ 2012'],
  },

  {
    id: 'cardio_icc_descompensada_eap',
    category: 'cardio',
    name: 'ICC Descompensada + Edema Agudo',
    description: 'Insuficiencia cardíaca aguda descompensada con edema agudo de pulmón cardiogénico. FE 25% conocida. FRCV: HTA, DM tipo 2, cardiopatía isquémica crónica. Ortopnea severa.',
    baseSeverity: 0.70,
    tags: ['ICC', 'EAP', 'Diuréticos', 'VNI', 'Furosemida'],
    pathologyConfigs: [
      { domain: 'cardio', subtype: 'icc_aguda_descompensada', baseSeverity: 0.70 },
      { domain: 'ards',   subtype: null,                       baseSeverity: 0.48 },
    ],
    initialVitals: {
      heartRate: 122,
      systolicBP: 105,
      diastolicBP: 72,
      meanArterialPressure: 83,
      cardiacOutput: 3.5,
      strokeVolume: 29,
      svr: 1844,
      cvp: 22,
      spo2: 85,
      respiratoryRate: 34,
      paO2: 58,
      paCO2: 35,
      pfRatio: 193,
      ardsActive: true,
      ardsSeverityLevel: 'MODERATE',
      icp: 12,
      gcs: 14,
      pupilState: 'reactive',
      lactate: 2.2,
      pH: 7.34,
      hco3: 21.5,
      baseExcess: -3.8,
      temperature: 36.4,
      urineOutput: 0.3,
      creatinine: 1.9,
    },
    isVentilatorConnected: false,
    recommendedRespSupport: 'hfnc',
    clinicalNotes: 'EAP cardiogénico: VNI como primera línea (CPAP/BiPAP reduce intubación NNT ~8). Furosemida IV 40–80 mg en bolo o infusión continua (DOSE trial). Nitroglicerina IV si PAS > 100 (reduce precarga y poscarga). Evitar sobrecarga hídrica. Vasodilatadores contraindicados si PAS < 90. Dobutamina si CO muy bajo. Considerar ultrafiltración si refractario a diuréticos.',
    references: ['Ponikowski P ESC HF 2016', 'DOSE Trial NEJM 2011', 'Felker GM NEJM 2011'],
  },

  {
    id: 'cardio_taponamiento_post_iam',
    category: 'cardio',
    name: 'Taponamiento Cardíaco Post-IAM',
    description: 'Hemopericardio tardío a las 72h de IAM anterior. Triada de Beck: hipotensión, ingurgitación yugular, tonos cardíacos apagados. Pulsus paradoxus 22 mmHg. Eco: derrame circunferencial 2 cm.',
    baseSeverity: 0.82,
    tags: ['Taponamiento', 'Hemopericardio', 'Pericardiocentesis', 'Beck', 'Shock obstructivo'],
    pathologyConfigs: [
      { domain: 'cardio', subtype: 'taponamiento', baseSeverity: 0.82 },
    ],
    initialVitals: {
      heartRate: 135,
      systolicBP: 78,
      diastolicBP: 58,
      meanArterialPressure: 65,
      cardiacOutput: 2.2,
      strokeVolume: 16,
      svr: 2310,
      cvp: 24,
      spo2: 91,
      respiratoryRate: 28,
      paO2: 75,
      paCO2: 35,
      pfRatio: 357,
      ardsActive: false,
      ardsSeverityLevel: 'NONE',
      icp: 12,
      gcs: 14,
      pupilState: 'reactive',
      lactate: 3.2,
      pH: 7.32,
      hco3: 19.5,
      baseExcess: -5.2,
      temperature: 36.5,
      urineOutput: 0.2,
      creatinine: 1.6,
    },
    isVentilatorConnected: false,
    recommendedRespSupport: 'simple_mask',
    clinicalNotes: 'Shock obstructivo puro: TRATAMIENTO DEFINITIVO = pericardiocentesis o ventana pericárdica quirúrgica. NO dilatar (nitratos, diuréticos) → caída crítica de precarga. Fluidos IV como puente temporal para mantener precarga. Dopamina/adrenalina para mantener FC y contractilidad mientras se organiza el drenaje. Evitar ventilación mecánica si posible (presión intratorácica negativa → beneficiosa).',
    references: ['Imazio M Eur Heart J 2014', 'Adler Y ESC 2015', 'Spodick DH NEJM 2003'],
  },

  {
    id: 'cardio_diseccion_aorta_stanford_a',
    category: 'cardio',
    name: 'Disección Aorta Stanford A',
    description: 'Disección aorta tipo A aguda (afecta aorta ascendente). Dolor torácico desgarrador irradiado a espalda. TA diferencial entre extremidades. Déficit neurológico transitorio. Cirugía urgente.',
    baseSeverity: 0.90,
    tags: ['Disección', 'Stanford A', 'Cirugía urgente', 'Labetalol', 'Regurgitación aórtica'],
    pathologyConfigs: [
      { domain: 'cardio', subtype: 'diseccion_aorta', baseSeverity: 0.90 },
    ],
    initialVitals: {
      heartRate: 118,
      systolicBP: 188,
      diastolicBP: 102,
      meanArterialPressure: 131,
      cardiacOutput: 5.2,
      strokeVolume: 44,
      svr: 1875,
      cvp: 10,
      spo2: 95,
      respiratoryRate: 24,
      paO2: 85,
      paCO2: 38,
      pfRatio: 405,
      ardsActive: false,
      ardsSeverityLevel: 'NONE',
      icp: 12,
      gcs: 14,
      pupilState: 'reactive',
      lactate: 2.8,
      pH: 7.36,
      hco3: 22.5,
      baseExcess: -2.5,
      temperature: 36.8,
      urineOutput: 0.6,
      creatinine: 1.4,
    },
    isVentilatorConnected: false,
    recommendedRespSupport: 'simple_mask',
    clinicalNotes: 'Control agresivo de FC y TAS: labetalol IV 20 mg bolo → infusión hasta FC < 60 lpm y SBP < 120 mmHg. Si contraindicación betabloqueante: diltiazem. NO usar vasodilatadores sin betabloqueante previo (aumenta dP/dt). Cirugía urgente Stanford A (mortalidad ~1–2% por hora sin cirugía). Angiografía/TC: confirmar extensión antes de OR. Preparar FFP y plaquetas para cirugía con circulación extracorpórea.',
    references: ['Erbel R ESC 2014', 'Nienaber CA NEJM 1999', 'Bavaria JE Ann Thorac Surg 2007'],
  },

  {
    id: 'cardio_tep_masivo',
    category: 'cardio',
    name: 'TEP Masivo con Inestabilidad',
    description: 'Tromboembolismo pulmonar masivo bilateral. Hipotensión refractaria. SpO₂ 82% con mascarilla. Dilatación VD en eco. Troponina I elevada × 8. Lactato 3.5.',
    baseSeverity: 0.88,
    tags: ['TEP', 'Masivo', 'tPA', 'VD', 'Heparina', 'ECMO'],
    pathologyConfigs: [
      { domain: 'cardio', subtype: 'tep_masivo', baseSeverity: 0.88 },
      { domain: 'ards',   subtype: null,          baseSeverity: 0.62 },
    ],
    initialVitals: {
      heartRate: 128,
      systolicBP: 82,
      diastolicBP: 48,
      meanArterialPressure: 59,
      cardiacOutput: 2.5,
      strokeVolume: 20,
      svr: 2153,
      cvp: 20,
      spo2: 82,
      respiratoryRate: 32,
      paO2: 52,
      paCO2: 30,
      pfRatio: 156,
      ardsActive: true,
      ardsSeverityLevel: 'MODERATE',
      icp: 12,
      gcs: 13,
      pupilState: 'reactive',
      lactate: 3.5,
      pH: 7.31,
      hco3: 18.5,
      baseExcess: -7.0,
      temperature: 36.2,
      urineOutput: 0.3,
      creatinine: 1.6,
    },
    isVentilatorConnected: false,
    recommendedRespSupport: 'hfnc',
    clinicalNotes: 'TEP masivo = hipotensión (< 90 mmHg × 15 min) o parada. Trombólisis sistémica: alteplase 100 mg/2h si sin contraindicaciones (muerte casi segura sin tratamiento supera riesgo sangrado). Heparina UFH 80 UI/kg bolo → 18 UI/kg/h, mantener durante trombólisis. Sobrecarga VD: evitar intubación si posible (elimina respiración espontánea que "aspira" sangre al VD). Volumen ≤ 500 mL (sobrecarga VD fatal).',
    references: ['Konstantinides SV ESC 2019', 'Meyer G NEJM PEITHO 2014', 'Steering AHA TEP 2011'],
  },

  {
    id: 'cardio_farva_aguda',
    category: 'cardio',
    name: 'FA con RVR — Sepsis (FARVA)',
    description: 'FA de nueva aparición con respuesta ventricular rápida (140 lpm) en contexto de sepsis abdominal. Descompensación hemodinámica. Intolerancia a betabloqueantes por hipotensión.',
    baseSeverity: 0.72,
    tags: ['FARVA', 'FA nueva', 'RVR', 'Amiodarona', 'Digoxina', 'Sepsis'],
    pathologyConfigs: [
      { domain: 'cardio', subtype: 'farva',   baseSeverity: 0.72 },
      { domain: 'sepsis', subtype: null,       baseSeverity: 0.60 },
    ],
    initialVitals: {
      heartRate: 140,
      systolicBP: 95,
      diastolicBP: 60,
      meanArterialPressure: 72,
      cardiacOutput: 4.8,
      strokeVolume: 34,
      svr: 1332,
      cvp: 7,
      spo2: 92,
      respiratoryRate: 24,
      paO2: 78,
      paCO2: 36,
      pfRatio: 371,
      ardsActive: false,
      ardsSeverityLevel: 'NONE',
      icp: 12,
      gcs: 14,
      pupilState: 'reactive',
      lactate: 2.8,
      pH: 7.30,
      hco3: 20.5,
      baseExcess: -5.2,
      temperature: 38.5,
      urineOutput: 0.4,
      creatinine: 1.6,
    },
    isVentilatorConnected: false,
    recommendedRespSupport: 'nasal_cannula',
    initialModifiers: {
      svrMultiplier: 0.72,
      capillaryLeakRate: 5.5,
      hyperdynamicFactor: 1.20,
      lungShuntFraction: 0.10,
      complianceMultiplier: 0.92,
    },
    clinicalNotes: 'FA nueva en UCI: incidencia 5–15%, asociada a mayor mortalidad. Betabloqueantes 1ª línea si FE preservada y hemodinámicamente estables (contraindicados en shock o broncoespasmo). Amiodarona si inestable: 150 mg IV en 10 min → 1 mg/min × 6h → 0.5 mg/min × 18h. Digoxina: alternativa en ICC o si β-bloq contraindicados; ventaja en sepsis: control FC sin inotropismo negativo. Diltiazem: superior a amiodarona en control FC (Siu 2009) pero contraindicado en ICC sistólica. Anticoagulación 24h post-FA si estable y sin contraindicación.',
    references: ['Bosch NA Chest 2020', 'Siu CW CCM 2009', 'Johnston BW BJA 2021', 'Gillmann HJ Sci Rep 2022'],
  },

  // ── Spec 3.C — FARVA puro (sin sepsis) ────────────────────────────────────
  {
    id: 'farva_aguda',
    category: 'cardio',
    name: 'FA con RVR Aguda',
    description: 'FA de nova aparición con respuesta ventricular rápida 155 lpm. Paciente 68 años hemodinámicamente limítrofe (MAP 77). Sin sepsis activa. Requiere rate control urgente.',
    baseSeverity: 0.60,
    tags: ['FA', 'RVR', 'Rate control', 'Amiodarona', 'Diltiazem', 'Esmolol'],
    pathologyConfigs: [
      { domain: 'cardio', subtype: 'farva', baseSeverity: 0.60 },
    ],
    initialVitals: {
      heartRate:             155,   // RVR típica 130-170 lpm (Johnston BJA 2021)
      systolicBP:            108,
      diastolicBP:            62,
      meanArterialPressure:   77,   // limítrofe — rate control urgente
      cardiacOutput:           3.8, // reducido por pérdida de patada auricular (~15-20%)
      strokeVolume:           25,   // CO/HR = 3.8/155 × 1000
      svr:                  1550,   // (77-8)*79.9/3.8 ≈ 1451 → ligero aumento compensatorio
      cvp:                     8,
      spo2:                   95,
      respiratoryRate:        22,
      paO2:                   83,
      paCO2:                  38,
      pfRatio:               395,
      ardsActive:          false,
      ardsSeverityLevel:  'NONE',
      icp:                    12,
      gcs:                    15,
      pupilState:        'reactive',
      lactate:               1.8,
      pH:                   7.38,
      hco3:                 22.5,
      baseExcess:           -2.0,
      temperature:          37.2,
      urineOutput:           0.7,
      creatinine:            1.2,
    },
    initialModifiers: {
      svrMultiplier:     1.05,   // leve vasoconstricción compensatoria
      hyperdynamicFactor: 1.0,
    },
    isVentilatorConnected: false,
    recommendedRespSupport: 'nasal_cannula',
    clinicalNotes: 'FA de novo con RVR: rate control 1ª prioridad (FC objetivo < 110 lpm). Decisión de fármaco según contexto: 1) FE preservada + estable → esmolol o diltiazem (Siu 2009: diltiazem > amio en control FC); 2) ICC sistólica → amiodarona o digoxina (BCC contraindicados); 3) Sepsis → amiodarona o digoxina (β-bloq evitar por hipotensión). Anticoagulación si FA > 48h o inestabilidad. Cardioversión eléctrica si hemodinámicamente inestable refractario.',
    references: ['Siu CW CCM 2009', 'Bosch NA Chest 2020', 'Kotecha D JAMA 2020'],
  },
];
