import type { ScenarioDefinition } from '../store/useScenarioStore';

// Valores MAP calculados: (SBP + 2×DBP) / 3
// Referencias: BTF 2016 (TCE), AHA/ASA HSA, AHA/ASA ACV

export const neuroCriticalScenarios: ScenarioDefinition[] = [
  {
    id: 'neuro_tce_grave',
    category: 'neuro',
    name: 'TCE Grave con HIC',
    description: 'Traumatismo craneoencefálico severo por accidente de tráfico. GCS 6, anisocoria derecha, reflejos troncoencefálicos conservados.',
    baseSeverity: 0.82,
    tags: ['TCE', 'HIC', 'Cushing', 'Neurocirugía'],
    pathologyConfigs: [
      { domain: 'neuroCritical', subtype: 'tce_grave', baseSeverity: 0.82 },
    ],
    initialVitals: {
      heartRate: 58,
      systolicBP: 172,
      diastolicBP: 98,
      meanArterialPressure: 123,
      cardiacOutput: 5.6,
      strokeVolume: 97,
      svr: 1620,
      cvp: 10,
      spo2: 96,
      respiratoryRate: 12,
      paO2: 92,
      paCO2: 34,
      pfRatio: 439,
      ardsActive: false,
      ardsSeverityLevel: 'NONE',
      icp: 34,
      gcs: 6,
      pupilState: 'unreactive',
      lactate: 2.4,
      pH: 7.37,
      hco3: 22.0,
      baseExcess: -2.2,
      temperature: 37.6,
      urineOutput: 0.8,
      creatinine: 1.1,
    },
    isVentilatorConnected: true,
    ventilatorPreset: {
      mode: 'VC-AC',
      fio2: 0.40,
      vt: 500,
      peep: 5,
      setRR: 14,
      pressureSupport: 0,
    },
    clinicalNotes: 'Triada de Cushing (HTA + bradicardia + irregularidad respiratoria). ICP objetivo < 22 mmHg (BTF 2016). PPC = MAP − ICP objetivo 60–70 mmHg. Cabecera 30°, normocapnia (PaCO₂ 35–40 mmHg). Hiperosmolar si herniación inminente. Considerar craniectomía descompresiva si refractario.',
    references: ['BTF 2016 Neurosurgery', 'Rangel-Castillo Neurosurg Clin 2008', 'Lee IEEE TBME 2016'],
  },

  {
    id: 'neuro_hsa_fisher4',
    category: 'neuro',
    name: 'HSA Fisher IV + Vasoespasmo',
    description: 'Hemorragia subaracnoidea Fisher IV por rotura de aneurisma de comunicante anterior. Vasoespasmo diferido día 5.',
    baseSeverity: 0.85,
    tags: ['HSA', 'Vasoespasmo', 'Aneurisma', 'Nimodipino'],
    pathologyConfigs: [
      { domain: 'neuroCritical', subtype: 'hsa', baseSeverity: 0.85 },
      { domain: 'sepsis', subtype: null, baseSeverity: 0.20 },
    ],
    initialVitals: {
      heartRate: 78,
      systolicBP: 182,
      diastolicBP: 98,
      meanArterialPressure: 126,
      cardiacOutput: 5.8,
      strokeVolume: 74,
      svr: 1638,
      cvp: 9,
      spo2: 95,
      respiratoryRate: 18,
      paO2: 85,
      paCO2: 38,
      pfRatio: 405,
      ardsActive: false,
      ardsSeverityLevel: 'NONE',
      icp: 26,
      gcs: 8,
      pupilState: 'sluggish',
      lactate: 1.8,
      pH: 7.38,
      hco3: 23.0,
      baseExcess: -1.0,
      temperature: 37.8,
      urineOutput: 0.7,
      creatinine: 1.0,
    },
    isVentilatorConnected: true,
    ventilatorPreset: {
      mode: 'VC-AC',
      fio2: 0.45,
      vt: 500,
      peep: 5,
      setRR: 14,
    },
    clinicalNotes: 'Vasoespasmo cerebral: peak días 4–14. Triple-H terapia (HTA permisiva + Hipervolemia + Hemodilución) controvertida; nimodipino 60mg/4h sí reduce déficit isquémico. Vigilar ECG (cambios ST/QTc por tono simpático). Drenar HSA si Fisher IV + hidrocefalia. PaCO₂ 35–40 mmHg, evitar hiperventilación que exacerba isquemia.',
    references: ['Diringer MN Stroke 2011', 'Connolly ES Stroke 2012', 'BTF 2016'],
  },

  {
    id: 'neuro_acv_isquemico_acm',
    category: 'neuro',
    name: 'ACV Isquémico ACM (Hemisférico)',
    description: 'Ictus isquémico hemisférico izquierdo por oclusión de arteria cerebral media. Dentro de ventana de trombólisis. NIHSS 18.',
    baseSeverity: 0.65,
    tags: ['ACV', 'Isquemia', 'ACM', 'tPA', 'Trombectomía'],
    pathologyConfigs: [
      { domain: 'neuroCritical', subtype: 'acv_isquemico', baseSeverity: 0.65 },
    ],
    initialVitals: {
      heartRate: 88,
      systolicBP: 168,
      diastolicBP: 92,
      meanArterialPressure: 117,
      cardiacOutput: 5.5,
      strokeVolume: 63,
      svr: 1538,
      cvp: 8,
      spo2: 96,
      respiratoryRate: 16,
      paO2: 90,
      paCO2: 40,
      pfRatio: 429,
      ardsActive: false,
      ardsSeverityLevel: 'NONE',
      icp: 14,
      gcs: 11,
      pupilState: 'reactive',
      lactate: 1.4,
      pH: 7.40,
      hco3: 24.0,
      baseExcess: 0.0,
      temperature: 37.2,
      urineOutput: 1.0,
      creatinine: 0.9,
    },
    isVentilatorConnected: false,
    recommendedRespSupport: 'nasal_cannula',
    clinicalNotes: 'HTA permisiva en ACV isquémico: objetivo < 185/110 si candidato a tPA; < 220/120 sin tPA. Glucemia objetivo 140–180 mg/dL. Fiebre empeora pronóstico (tratar si > 37.5°C). Hemicraniectomía descompresiva en infarto maligno de ACM (pacientes < 60 años, primeras 48h). Disfagia → riesgo aspiración → SNG.',
    references: ['Powers WJ AHA/ASA 2018', 'Vahedi K DESTINY 2007', 'Hacke W ECASS III 2008'],
  },

  {
    id: 'neuro_acv_hemorragico',
    category: 'neuro',
    name: 'ACV Hemorrágico (Putaminal)',
    description: 'Hemorragia intracerebral espontánea putaminal izquierda 35 mL. HTA crónica mal controlada. Hematoma con expansión.',
    baseSeverity: 0.72,
    tags: ['Hemorragia', 'Putamen', 'HTA', 'ICP', 'Reversión anticoag'],
    pathologyConfigs: [
      { domain: 'neuroCritical', subtype: 'acv_hemorragico', baseSeverity: 0.72 },
    ],
    initialVitals: {
      heartRate: 74,
      systolicBP: 196,
      diastolicBP: 112,
      meanArterialPressure: 140,
      cardiacOutput: 5.9,
      strokeVolume: 80,
      svr: 1854,
      cvp: 9,
      spo2: 96,
      respiratoryRate: 18,
      paO2: 90,
      paCO2: 39,
      pfRatio: 429,
      ardsActive: false,
      ardsSeverityLevel: 'NONE',
      icp: 22,
      gcs: 9,
      pupilState: 'sluggish',
      lactate: 1.6,
      pH: 7.39,
      hco3: 23.5,
      baseExcess: -0.8,
      temperature: 37.3,
      urineOutput: 0.8,
      creatinine: 1.1,
    },
    isVentilatorConnected: true,
    ventilatorPreset: {
      mode: 'VC-AC',
      fio2: 0.40,
      vt: 490,
      peep: 5,
      setRR: 14,
    },
    clinicalNotes: 'AHA 2022: SBP objetivo < 140 mmHg en primeras horas si hematoma ≤ 60 mL y sin contraindicación. Reversión anticoagulantes urgente (CCP 4F si AVK; idarucizumab si dabigatrán). Monitorización ICP si GCS ≤ 8. Expansión hematoma primeras 24h (10–38%): factores de riesgo: antiplaquetario, anticoag, coagulopatía.',
    references: ['Greenberg SM AHA 2022 Stroke', 'Frontera JA Neurocrit Care 2016'],
  },

  {
    id: 'neuro_status_epileptico',
    category: 'neuro',
    name: 'Status Epiléptico Refractario',
    description: 'Status epiléptico convulsivo que no responde a 2 benzodiazepinas y 1 antiepiléptico de segunda línea. Hiperpirexia por actividad motora mantenida.',
    baseSeverity: 0.78,
    tags: ['Status', 'Epilepsia', 'Refractario', 'Barbitúrico', 'ACLS'],
    pathologyConfigs: [
      { domain: 'neuroCritical', subtype: 'status_epileptico', baseSeverity: 0.78 },
      { domain: 'sepsis', subtype: null, baseSeverity: 0.15 },
    ],
    initialVitals: {
      heartRate: 132,
      systolicBP: 152,
      diastolicBP: 88,
      meanArterialPressure: 109,
      cardiacOutput: 7.2,
      strokeVolume: 55,
      svr: 1290,
      cvp: 6,
      spo2: 88,
      respiratoryRate: 26,
      paO2: 65,
      paCO2: 46,
      pfRatio: 155,
      ardsActive: true,
      ardsSeverityLevel: 'MODERATE',
      icp: 18,
      gcs: 5,
      pupilState: 'miotic',
      lactate: 9.2,
      pH: 7.21,
      hco3: 18.0,
      baseExcess: -8.5,
      temperature: 40.4,
      urineOutput: 0.4,
      creatinine: 1.6,
    },
    isVentilatorConnected: true,
    ventilatorPreset: {
      mode: 'VC-AC',
      fio2: 0.60,
      vt: 420,
      peep: 8,
      setRR: 20,
    },
    clinicalNotes: 'Acidosis láctica severa por actividad muscular: remite con cese de crisis. Hiperpirexia empeora lesión neuronal (tratar agresivamente). Status refractario: propofol/midazolam/barbitúrico en infusión. Contraindicado ketamina relativa en epilepsia (pero puede usarse en refractario). EEG continuo durante tratamiento.',
    references: ['Trinka E Epilepsia 2015', 'Glauser T Epilepsy Curr 2016'],
  },

  {
    id: 'neuro_meningitis_bacteriana',
    category: 'neuro',
    name: 'Meningitis Neumocócica',
    description: 'Meningitis bacteriana por Streptococcus pneumoniae. Triada clásica completa: fiebre, rigidez nucal, alteración de consciencia. Convulsiones en urgencias.',
    baseSeverity: 0.70,
    tags: ['Meningitis', 'Neumococo', 'Sepsis', 'Dexametasona', 'Urgencia'],
    pathologyConfigs: [
      { domain: 'neuroCritical', subtype: 'meningitis_bacteriana', baseSeverity: 0.70 },
      { domain: 'sepsis', subtype: null, baseSeverity: 0.55 },
    ],
    initialVitals: {
      heartRate: 120,
      systolicBP: 95,
      diastolicBP: 58,
      meanArterialPressure: 70,
      cardiacOutput: 6.8,
      strokeVolume: 57,
      svr: 948,
      cvp: 5,
      spo2: 94,
      respiratoryRate: 24,
      paO2: 78,
      paCO2: 34,
      pfRatio: 371,
      ardsActive: false,
      ardsSeverityLevel: 'NONE',
      icp: 22,
      gcs: 9,
      pupilState: 'reactive',
      lactate: 3.6,
      pH: 7.28,
      hco3: 19.5,
      baseExcess: -5.8,
      temperature: 40.1,
      urineOutput: 0.3,
      creatinine: 1.8,
    },
    isVentilatorConnected: false,
    recommendedRespSupport: 'simple_mask',
    clinicalNotes: 'ATB + dexametasona ANTES si posible, no retrasar > 30 min por pruebas. Ceftriaxona 2g/12h + dexametasona 0.15 mg/kg/6h × 4 días. TC antes de PL solo si foco neurológico/papiledema/convulsiones/inmunodeprimido. Drenaje LCR urgente si HIC. Mortalidad ~25% si S. pneumoniae. Secuelas: sordera 30%.',
    references: ['van de Beek D NEJM 2016', 'Tunkel AR IDSA 2004', 'de Gans J NEJM 2002'],
  },

  // ── Escenarios con catéter PIC / DVE ───────────────────────────────────────

  {
    id: 'neuro_hsa_fisher_iv',
    category: 'neuro',
    name: 'HSA Fisher IV con DVE',
    description: 'Hemorragia subaracnoidea aneurismática Fisher IV (sangre intraventricular). Drenaje ventricular externo activo. Vasoespasmo precoz.',
    baseSeverity: 0.88,
    tags: ['HSA', 'Aneurisma', 'DVE', 'Vasoespasmo', 'Fisher IV'],
    icpCatheterRequired: true,
    icpCatheterType: 'intraventricular',
    evdActive: true,
    icpDrainageThreshold_mmHg: 20,
    pathologyConfigs: [
      { domain: 'neuroCritical', subtype: 'hsa_aneurysmal', baseSeverity: 0.88 },
    ],
    initialVitals: {
      heartRate: 88, systolicBP: 168, diastolicBP: 102,
      meanArterialPressure: 124, cardiacOutput: 5.8, strokeVolume: 66,
      svr: 1560, cvp: 9,
      spo2: 95, respiratoryRate: 18,
      paO2: 88, paCO2: 36, pfRatio: 380,
      ardsActive: false, ardsSeverityLevel: 'NONE',
      icp: 28, gcs: 8,
      pupilState: 'sluggish',
      lactate: 1.8, pH: 7.38, hco3: 22.0, baseExcess: -2.0,
      temperature: 37.8, creatinine: 0.9, urineOutput: 0.7,
    },
    clinicalNotes: 'Nimodipino 60 mg/4h VO/SNG (Pickard Lancet 1989). Target PPC 70 mmHg. Drenaje EVD si PIC > 20. Embolización del aneurisma pendiente (pendiente estado hemodinámica).',
    references: [
      'Diringer MN et al. Crit Care Med 2011;39:2235 — manejo HSA en UCI',
      'Connolly ES et al. Stroke 2012;43:1711 — guías AHA/ASA HSA',
    ],
  },
  {
    id: 'neuro_acv_maligno_descomp',
    category: 'neuro',
    name: 'ACV ACM Maligno Descomp.',
    description: 'Infarto maligno de ACM con efecto de masa. PO de craneotomía descompresiva. Monitoreo PIC parenquimatoso. Edema hemisférico severo.',
    baseSeverity: 0.85,
    tags: ['ACV', 'ACM', 'Craneotomía', 'PIC', 'Descompresiva'],
    icpCatheterRequired: true,
    icpCatheterType: 'parenchymal',
    evdActive: false,
    icpDrainageThreshold_mmHg: 22,
    pathologyConfigs: [
      { domain: 'neuroCritical', subtype: 'ischemic_stroke', baseSeverity: 0.85 },
    ],
    initialVitals: {
      heartRate: 66, systolicBP: 148, diastolicBP: 88,
      meanArterialPressure: 108, cardiacOutput: 5.0, strokeVolume: 76,
      svr: 1560, cvp: 8,
      spo2: 94, respiratoryRate: 20,
      paO2: 78, paCO2: 38, pfRatio: 252,
      ardsActive: false, ardsSeverityLevel: 'NONE',
      icp: 24, gcs: 7, pupilState: 'sluggish',
      lactate: 1.4, pH: 7.38, hco3: 22.5, baseExcess: -1.5,
      temperature: 37.5, creatinine: 1.0, urineOutput: 0.7,
    },
    recommendedRespSupport: 'arm',
    isVentilatorConnected: true,
    ventilatorPreset: { fio2: 0.40, peep: 5, vt: 480, setRR: 14, mode: 'VC-AC' },
    clinicalNotes: 'Target PPC ≥ 70 mmHg. Cabecera 30°. Hiperventilación suave si PIC > 25 (PaCO₂ 32-35). Osmoterapia manitol 20% 1g/kg. No corticoides (HAMLET trial).',
    references: [
      'Vahedi K et al. Lancet Neurol 2007;6:215 — descompresiva ACV maligno',
      'Wijdicks EFM et al. Neurocrit Care 2008;8:113',
    ],
  },
  {
    id: 'neuro_status_epilepticus',
    category: 'neuro',
    name: 'Status Epiléptico Refractario',
    description: 'Status epiléptico refractario no convulsivo. EEG continuo con actividad NCSE. Sedoanalgesia profunda. Monitoreo invasivo por riesgo HIC.',
    baseSeverity: 0.80,
    tags: ['Status', 'NCSE', 'EEG', 'Refractario', 'HIC'],
    icpCatheterRequired: false,
    evdActive: false,
    pathologyConfigs: [
      { domain: 'neuroCritical', subtype: 'status_epilepticus', baseSeverity: 0.80 },
    ],
    initialVitals: {
      heartRate: 108, systolicBP: 142, diastolicBP: 86,
      meanArterialPressure: 105, cardiacOutput: 6.2, strokeVolume: 57,
      svr: 1240, cvp: 8,
      spo2: 93, respiratoryRate: 24,
      paO2: 70, paCO2: 42, pfRatio: 210,
      ardsActive: false, ardsSeverityLevel: 'NONE',
      icp: 18, gcs: 6, pupilState: 'reactive',
      lactate: 3.2, pH: 7.30, hco3: 20.0, baseExcess: -6.0,
      temperature: 38.6, creatinine: 1.2, urineOutput: 0.55,
    },
    recommendedRespSupport: 'arm',
    isVentilatorConnected: true,
    ventilatorPreset: { fio2: 0.40, peep: 5, vt: 460, setRR: 14, mode: 'VC-AC' },
    clinicalNotes: 'Propofol 3-5 mg/kg/h + midazolam infusión. Monitoreo EEG continuo → burst suppression como target. K+ y Mg vigilar (epileptogénicos). Considerar ketamina si refractario.',
    references: [
      'Brophy GM et al. Neurocrit Care 2012;17:3 — guías NCSE',
      'Trinka E et al. Epilepsia 2015;56:1515 — definición ILAE',
    ],
  },
  {
    id: 'neuro_edema_postanoxia',
    category: 'neuro',
    name: 'Edema Cerebral Postanóxico',
    description: 'PCR reanimada 15 min sin flujo. Hipotermia terapéutica completada (33°C × 24h). Síndrome postparo cardíaco con coma anóxico. PIC 30 mmHg.',
    baseSeverity: 0.90,
    tags: ['Postparo', 'Anoxia', 'HIC', 'Hipotermia', 'PCR'],
    icpCatheterRequired: true,
    icpCatheterType: 'parenchymal',
    evdActive: false,
    icpDrainageThreshold_mmHg: 22,
    pathologyConfigs: [
      { domain: 'neuroCritical', subtype: 'anoxic_injury', baseSeverity: 0.90 },
      { domain: 'cardio',   subtype: 'post_cardiac_arrest', baseSeverity: 0.70 },
    ],
    initialVitals: {
      heartRate: 72, systolicBP: 130, diastolicBP: 78,
      meanArterialPressure: 95, cardiacOutput: 5.2, strokeVolume: 72,
      svr: 1340, cvp: 9,
      spo2: 97, respiratoryRate: 14,
      paO2: 110, paCO2: 40, pfRatio: 392,
      ardsActive: false, ardsSeverityLevel: 'NONE',
      icp: 30, gcs: 3, pupilState: 'unreactive',
      lactate: 2.8, pH: 7.36, hco3: 22.5, baseExcess: -2.0,
      temperature: 36.0, creatinine: 1.4, urineOutput: 0.6,
    },
    recommendedRespSupport: 'arm',
    isVentilatorConnected: true,
    ventilatorPreset: { fio2: 0.35, peep: 5, vt: 500, setRR: 12, mode: 'VC-AC' },
    clinicalNotes: 'TTM completo (33°C × 24h). NSE elevada. EEG: actividad supresión. Pronóstico: ausencia bilateral P300 + NSE > 60 mcg/L → supervivencia < 10% (Sandroni Resuscitation 2014). Discutir con familia.',
    references: [
      'Nolan JP et al. Resuscitation 2021;161:337 — ERC/ESICM postresucitación',
      'Sandroni C et al. Resuscitation 2014;85:1324 — pronóstico coma postanóxico',
    ],
  },
  {
    id: 'neuro_mielitis_bulbar',
    category: 'neuro',
    name: 'Mielitis Transversa Bulbar',
    description: 'Mielitis transversa cervical alta (C3-C5) con compromiso bulbar. Cuadriplejía + insuficiencia respiratoria neurogénica. IRM: lesión LETM.',
    baseSeverity: 0.78,
    tags: ['Mielitis', 'Cervical', 'LETM', 'Bulbar', 'Ventilación'],
    icpCatheterRequired: false,
    evdActive: false,
    pathologyConfigs: [
      { domain: 'neuroCritical', subtype: 'spinal_cord', baseSeverity: 0.78 },
      { domain: 'pneumonia',    subtype: 'neuro_resp_failure', baseSeverity: 0.75 },
    ],
    initialVitals: {
      heartRate: 62, systolicBP: 92, diastolicBP: 56,
      meanArterialPressure: 68, cardiacOutput: 4.2, strokeVolume: 68,
      svr: 1180, cvp: 5,
      spo2: 88, respiratoryRate: 28,
      paO2: 55, paCO2: 52, pfRatio: 172,
      ardsActive: false, ardsSeverityLevel: 'NONE',
      icp: 12, gcs: 11, pupilState: 'reactive',
      lactate: 1.6, pH: 7.28, hco3: 24.0, baseExcess: -2.5,
      temperature: 37.2, creatinine: 0.8, urineOutput: 0.8,
    },
    recommendedRespSupport: 'arm',
    isVentilatorConnected: true,
    ventilatorPreset: { fio2: 0.50, peep: 8, vt: 420, setRR: 16, mode: 'VC-AC' },
    clinicalNotes: 'Metilprednisolona 1 g/d × 3d (Kumar J Neuroimmunol 2019). Descartar NMO-IgG/MOG-Ab. Plasmaféresis si refractaria a corticoides. PVC → neurológica, no cardíaca.',
    references: [
      'Transverse Myelitis Consortium Working Group. Neurology 2002;59:499',
      'Kumar N et al. J Neuroimmunol 2019;329 — tratamiento mielitis transversa',
    ],
  },
];
