import type { ScenarioDefinition } from '../store/useScenarioStore';

// Referencias: ATLS 11th Ed.; PROPPR (Holcomb JAMA 2015); EAST Guidelines
// Nota: las tasas de sangrado del store (8/20/45/90 mL/min) corresponden a
// CLASS_HEMORRHAGE_RATES — ATLS 11ª Ed. (Cannon NEJM 2018).

export const polytraumaScenarios: ScenarioDefinition[] = [
  {
    id: 'trauma_tce_aislado',
    category: 'trauma',
    name: 'TCE Aislado (Contusión Frontal)',
    description: 'Traumatismo craneal aislado por caída desde altura. Contusión frontal bilateral + hematoma epidural temporal derecho 25 mL. Hemorragia mínima. GCS 9.',
    baseSeverity: 0.62,
    tags: ['TCE', 'Epidural', 'Contusión', 'Neurocirugía', 'ICP'],
    pathologyConfigs: [
      { domain: 'neuroCritical',   subtype: 'tce_aislado', baseSeverity: 0.62 },
      { domain: 'polytrauma',      subtype: 'tce_aislado', baseSeverity: 0.62 },
      { domain: 'hemorrhagicShock', subtype: '1',          baseSeverity: 0.20 },
    ],
    initialVitals: {
      heartRate: 72,
      systolicBP: 148,
      diastolicBP: 88,
      meanArterialPressure: 108,
      cardiacOutput: 5.5,
      strokeVolume: 76,
      svr: 1482,
      cvp: 8,
      spo2: 97,
      respiratoryRate: 14,
      paO2: 90,
      paCO2: 38,
      pfRatio: 429,
      ardsActive: false,
      ardsSeverityLevel: 'NONE',
      icp: 24,
      gcs: 9,
      pupilState: 'sluggish',
      lactate: 1.8,
      pH: 7.38,
      hco3: 22.5,
      baseExcess: -2.0,
      temperature: 37.0,
      urineOutput: 0.8,
      creatinine: 0.9,
    },
    isVentilatorConnected: true,
    ventilatorPreset: {
      mode: 'VC-AC',
      fio2: 0.40,
      vt: 490,
      peep: 5,
      setRR: 14,
    },
    initialBloodVolumeMl: 4650,
    clinicalNotes: 'Hematoma epidural con efecto de masa: evacuación quirúrgica si grosor > 10 mm o desplazamiento línea media > 5 mm. Control ICP: cabecera 30°, analgesia, normocapnia (PaCO₂ 35–40), osmoterapia. Evitar hipotensión (MAP objetivo 80 mmHg con ICP elevada). Profilaxis convulsiones 7 días.',
    references: ['BTF 2016 Neurosurgery', 'Carney N BTF 2016'],
  },

  {
    id: 'trauma_tce_torax',
    category: 'trauma',
    name: 'TCE + Trauma Torácico',
    description: 'Accidente de tráfico. TCE moderado GCS 10 + contusión pulmonar bilateral + neumotórax derecho drenado. Clase II hemorrágica.',
    baseSeverity: 0.72,
    tags: ['TCE', 'Contusión pulmonar', 'Neumotórax', 'Clase II', 'Politrauma'],
    pathologyConfigs: [
      { domain: 'neuroCritical',    subtype: 'tce_moderado', baseSeverity: 0.55 },
      { domain: 'polytrauma',       subtype: 'tce_torax',    baseSeverity: 0.72 },
      { domain: 'ards',             subtype: null,           baseSeverity: 0.38 },
      { domain: 'hemorrhagicShock', subtype: '2',            baseSeverity: 0.50 },
    ],
    initialVitals: {
      heartRate: 110,
      systolicBP: 100,
      diastolicBP: 62,
      meanArterialPressure: 75,
      cardiacOutput: 5.2,
      strokeVolume: 47,
      svr: 1085,
      cvp: 5,
      spo2: 92,
      respiratoryRate: 24,
      paO2: 68,
      paCO2: 38,
      pfRatio: 227,
      ardsActive: true,
      ardsSeverityLevel: 'MODERATE',
      icp: 18,
      gcs: 10,
      pupilState: 'reactive',
      lactate: 3.5,
      pH: 7.31,
      hco3: 20.0,
      baseExcess: -5.5,
      temperature: 36.5,
      urineOutput: 0.5,
      creatinine: 1.2,
    },
    isVentilatorConnected: true,
    ventilatorPreset: {
      mode: 'VC-AC',
      fio2: 0.55,
      vt: 420,
      peep: 8,
      setRR: 18,
    },
    initialBloodVolumeMl: 4100,
    clinicalNotes: 'Tensión fisiopatológica TCE-trauma torácico: ventilación protectora puede causar hipercapnia permisiva que aumenta PIC. Objetivo: PaCO₂ 35–40 mmHg en TCE grave. Contusión pulmonar empeora primeras 24–48h. PEEP moderado (6–10) para reclutamiento sin aumentar PIC. Transfusión 1:1:1 si hemorragia clase III o mayor.',
    references: ['BTF 2016', 'EAST Guidelines 2017', 'PROPPR Holcomb 2015'],
  },

  {
    id: 'trauma_tce_abdomen_pelvis',
    category: 'trauma',
    name: 'TCE + Abdomen + Pelvis',
    description: 'Politrauma masivo. TCE grave (GCS 7) + rotura esplénica grado IV + fractura de pelvis inestable (Tile B). Clase III hemorrágica.',
    baseSeverity: 0.88,
    tags: ['Politrauma', 'Bazo', 'Pelvis', 'Clase III', 'Damage Control'],
    pathologyConfigs: [
      { domain: 'neuroCritical',    subtype: 'tce_grave',        baseSeverity: 0.70 },
      { domain: 'polytrauma',       subtype: 'tce_torax_abdomen', baseSeverity: 0.88 },
      { domain: 'hemorrhagicShock', subtype: '3',                baseSeverity: 0.75 },
      { domain: 'ards',             subtype: null,               baseSeverity: 0.42 },
    ],
    initialVitals: {
      heartRate: 136,
      systolicBP: 80,
      diastolicBP: 48,
      meanArterialPressure: 59,
      cardiacOutput: 5.8,
      strokeVolume: 43,
      svr: 908,
      cvp: 3,
      spo2: 90,
      respiratoryRate: 28,
      paO2: 62,
      paCO2: 36,
      pfRatio: 207,
      ardsActive: true,
      ardsSeverityLevel: 'MODERATE',
      icp: 22,
      gcs: 7,
      pupilState: 'sluggish',
      lactate: 6.8,
      pH: 7.20,
      hco3: 15.0,
      baseExcess: -11.5,
      temperature: 35.8,
      urineOutput: 0.2,
      creatinine: 1.8,
    },
    isVentilatorConnected: true,
    ventilatorPreset: {
      mode: 'VC-AC',
      fio2: 0.60,
      vt: 420,
      peep: 8,
      setRR: 20,
    },
    initialBloodVolumeMl: 3200,
    clinicalNotes: 'Tríada letal: hipotermia (< 36°C) + acidosis (BE < −6) + coagulopatía (QUICK < 50%). Damage Control: cirugía abreviada → UCI → reciclaje correcto → cirugía definitiva. Protocolo 1:1:1 GRE:PFC:PLT. Sábana o fijador externo para pelvis. MAP objetivo 50–60 mmHg hasta control quirúrgico (hipotensión permisiva excepto TCE). Calcio IV si hipocalcemia por transfusión masiva.',
    references: ['PROPPR Holcomb JAMA 2015', 'EAST Guidelines 2017', 'BTF 2016', 'EAST Pelvic Fracture 2011'],
  },

  {
    id: 'trauma_fulminante_clase3',
    category: 'trauma',
    name: 'Politrauma Fulminante — Clase III',
    description: 'Atrapamiento vehicular 20 min. Aplastamiento tórax-abdomen. Clase III hemorrágica activa. Hipotermia 35.2°C. FAST positivo. ECG: SaO₂ indetectable.',
    baseSeverity: 0.93,
    tags: ['Clase III', 'Exanguinación', 'Aplastamiento', 'Damage Control', 'FAST'],
    pathologyConfigs: [
      { domain: 'polytrauma',       subtype: 'tce_torax_abdomen', baseSeverity: 0.93 },
      { domain: 'hemorrhagicShock', subtype: '3',                 baseSeverity: 0.88 },
      { domain: 'ards',             subtype: null,                baseSeverity: 0.55 },
    ],
    initialVitals: {
      heartRate: 148,
      systolicBP: 72,
      diastolicBP: 40,
      meanArterialPressure: 51,
      cardiacOutput: 4.8,
      strokeVolume: 32,
      svr: 890,
      cvp: 2,
      spo2: 86,
      respiratoryRate: 34,
      paO2: 54,
      paCO2: 38,
      pfRatio: 135,
      ardsActive: true,
      ardsSeverityLevel: 'SEVERE',
      icp: 12,
      gcs: 8,
      pupilState: 'reactive',
      lactate: 10.5,
      pH: 7.14,
      hco3: 12.0,
      baseExcess: -15.0,
      temperature: 35.2,
      urineOutput: 0.0,
      creatinine: 2.5,
    },
    isVentilatorConnected: true,
    ventilatorPreset: {
      mode: 'VC-AC',
      fio2: 0.80,
      vt: 400,
      peep: 8,
      setRR: 20,
    },
    initialBloodVolumeMl: 2900,
    clinicalNotes: 'Activar protocolo transfusión masiva (PTM). Objetivo: temperatura > 36°C (calentamiento activo), pH > 7.20, QUICK > 50%, fibrinógeno > 1.5 g/L. Ácido tranexámico 1g IV en < 3h del trauma. Vasopresores solo como puente a control quirúrgico. REBOA si fractura pélvica o lesión retroperitoneal con shock refractario.',
    references: ['PROPPR 2015', 'CRASH-2 Lancet 2010', 'Holcomb JC Arch Surg 2011'],
  },
];
