import type { ScenarioDefinition } from '../store/useScenarioStore';

// Referencias: Berlin 2012 (SDRA); GOLD 2024 (EPOC); GINA 2024 (asma)
// P/F calculado: paO2 / fio2Effective
// Todos los pacientes en ventilación mecánica excepto EPOC no intubado

export const respiratoryScenarios: ScenarioDefinition[] = [
  {
    id: 'resp_neumonia_bacteriana_sdra',
    category: 'respiratory',
    name: 'Neumonía Bacteriana → SDRA Moderado',
    description: 'Neumonía lobar por Klebsiella pneumoniae con progresión a SDRA moderado en 48h. FiO₂ 0.70 necesaria. P/F 145. Leucocitosis 22.000.',
    baseSeverity: 0.75,
    tags: ['Neumonía', 'SDRA', 'Klebsiella', 'Berlín Moderado', 'VAC'],
    pathologyConfigs: [
      { domain: 'ards',      subtype: null,         baseSeverity: 0.65 },
      { domain: 'pneumonia', subtype: 'bacteriana',  baseSeverity: 0.75 },
      { domain: 'sepsis',    subtype: null,          baseSeverity: 0.45 },
    ],
    initialVitals: {
      heartRate: 105,
      systolicBP: 105,
      diastolicBP: 62,
      meanArterialPressure: 76,
      cardiacOutput: 6.5,
      strokeVolume: 62,
      svr: 1060,
      cvp: 7,
      spo2: 92,
      respiratoryRate: 24,
      paO2: 72,
      paCO2: 38,
      pfRatio: 103,
      ardsActive: true,
      ardsSeverityLevel: 'SEVERE',
      icp: 12,
      gcs: 13,
      pupilState: 'reactive',
      lactate: 2.8,
      pH: 7.30,
      hco3: 20.5,
      baseExcess: -4.8,
      temperature: 38.8,
      urineOutput: 0.5,
      creatinine: 1.4,
    },
    isVentilatorConnected: true,
    ventilatorPreset: {
      mode: 'VC-AC',
      fio2: 0.70,
      vt: 420,
      peep: 10,
      setRR: 20,
    },
    initialModifiers: {
      svrMultiplier: 0.75,
      capillaryLeakRate: 4.5,
      hyperdynamicFactor: 1.15,
      lungShuntFraction: 0.48,
      complianceMultiplier: 0.50,
    },
    clinicalNotes: 'Ventilación protectora SDRA: VT 6 mL/kg PBW, Pplat < 30 cmH₂O, ΔP < 15 cmH₂O. PEEP según tabla FiO₂/PEEP ARDSNet. Considerar prone si P/F < 150 sostenido > 12h con PEEP ≥ 5. BNM 48h si P/F < 150 con FiO₂ > 0.60 (controversia post-ACURASYS/ROSE). ATB empírico: ceftriaxona + azitromicina; ajustar a cultivos.',
    references: ['Berlin JAMA 2012', 'ARDSNet NEJM 2000', 'Guérin NEJM 2013'],
  },

  {
    id: 'resp_neumonia_viral_covid',
    category: 'respiratory',
    name: 'Neumonía Viral (Influenza / COVID-like)',
    description: 'Neumonía viral bilateral severa con opacidades en vidrio deslustrado y consolidaciones periféricas. Hipoxemia progresiva. Paciente joven, sin comorbilidades.',
    baseSeverity: 0.70,
    tags: ['Viral', 'COVID', 'Influenza', 'SDRA', 'Prone', 'Hipoxemia'],
    pathologyConfigs: [
      { domain: 'ards',      subtype: null,   baseSeverity: 0.72 },
      { domain: 'pneumonia', subtype: 'viral', baseSeverity: 0.70 },
      { domain: 'sepsis',    subtype: null,    baseSeverity: 0.30 },
    ],
    initialVitals: {
      heartRate: 98,
      systolicBP: 108,
      diastolicBP: 65,
      meanArterialPressure: 79,
      cardiacOutput: 6.2,
      strokeVolume: 63,
      svr: 1144,
      cvp: 6,
      spo2: 90,
      respiratoryRate: 28,
      paO2: 65,
      paCO2: 36,
      pfRatio: 130,
      ardsActive: true,
      ardsSeverityLevel: 'SEVERE',
      icp: 12,
      gcs: 14,
      pupilState: 'reactive',
      lactate: 2.2,
      pH: 7.34,
      hco3: 21.5,
      baseExcess: -3.5,
      temperature: 38.2,
      urineOutput: 0.7,
      creatinine: 1.1,
    },
    isVentilatorConnected: true,
    ventilatorPreset: {
      mode: 'VC-AC',
      fio2: 0.75,
      vt: 420,
      peep: 10,
      setRR: 20,
    },
    initialModifiers: {
      svrMultiplier: 0.82,
      capillaryLeakRate: 3.5,
      hyperdynamicFactor: 1.10,
      lungShuntFraction: 0.52,
      complianceMultiplier: 0.52,
    },
    clinicalNotes: 'SDRA viral: fenotipo H (alta compliance, alta recruitabilidad) vs L (baja compliance, baja recruitabilidad). Estrategia inicial: posición prona si P/F < 150. Dexametasona en neumonía severa COVID. HFNC como alternativa a intubación en hipoxemia moderada. Monitorizar esfuerzo respiratorio (P0.1, Pocc): esfuerzo excesivo puede causar P-SILI.',
    references: ['Gattinoni L Intensive Care Med 2020', 'RECOVERY Dexamethasone NEJM 2021', 'Berlin 2012'],
  },

  {
    id: 'resp_neumonia_fungica_inmunodeprimido',
    category: 'respiratory',
    name: 'Neumonía Fúngica en Inmunodeprimido',
    description: 'Aspergilosis pulmonar invasora en paciente post-trasplante de médula ósea. Nódulos con halo en TC. Galactomanano positivo. SpO₂ 88% con mascarilla reservorio.',
    baseSeverity: 0.72,
    tags: ['Aspergilosis', 'Inmunodeprimido', 'TMO', 'Voriconazol', 'SDRA'],
    pathologyConfigs: [
      { domain: 'ards',      subtype: null,    baseSeverity: 0.68 },
      { domain: 'pneumonia', subtype: 'fungica', baseSeverity: 0.72 },
      { domain: 'sepsis',    subtype: null,    baseSeverity: 0.35 },
    ],
    initialVitals: {
      heartRate: 102,
      systolicBP: 105,
      diastolicBP: 62,
      meanArterialPressure: 76,
      cardiacOutput: 6.0,
      strokeVolume: 59,
      svr: 1118,
      cvp: 6,
      spo2: 88,
      respiratoryRate: 26,
      paO2: 62,
      paCO2: 36,
      pfRatio: 124,
      ardsActive: true,
      ardsSeverityLevel: 'SEVERE',
      icp: 12,
      gcs: 14,
      pupilState: 'reactive',
      lactate: 2.5,
      pH: 7.32,
      hco3: 20.8,
      baseExcess: -4.2,
      temperature: 38.5,
      urineOutput: 0.5,
      creatinine: 1.3,
    },
    isVentilatorConnected: true,
    ventilatorPreset: {
      mode: 'VC-AC',
      fio2: 0.70,
      vt: 420,
      peep: 10,
      setRR: 20,
    },
    initialModifiers: {
      svrMultiplier: 0.80,
      capillaryLeakRate: 4.0,
      hyperdynamicFactor: 1.12,
      lungShuntFraction: 0.50,
      complianceMultiplier: 0.48,
    },
    clinicalNotes: 'Voriconazol 6 mg/kg/12h × 1 día → 4 mg/kg/12h (monitorizar niveles: objetivo 1–5.5 mg/L). Alternativa: isavuconazol (menos hepatotóxico). Interacciones CYP: voriconazol + tacrolimus → toxicidad tacrolimus. Neutropenia: factores de crecimiento G-CSF. Fallo de voriconazol → añadir caspofungina (sinergia sinérgica documentada).',
    references: ['Patterson TF IDSA 2016', 'Herbrecht R NEJM 2002', 'Marr KA Blood 2021'],
  },

  {
    id: 'resp_status_asthmaticus',
    category: 'respiratory',
    name: 'Status Asthmaticus Intubado',
    description: 'Asma grave refractaria a tratamiento en urgencias. Intubación de urgencia con broncospasmo severo post-intubación. PaCO₂ 52 mmHg en aumento. Hiperinflación dinámica.',
    baseSeverity: 0.80,
    tags: ['Status', 'Asthmaticus', 'AutoPEEP', 'Broncospasmo', 'Ketamina'],
    pathologyConfigs: [
      { domain: 'asthma', subtype: 'status_asthmaticus', baseSeverity: 0.80 },
      { domain: 'ards',   subtype: null,                 baseSeverity: 0.25 },
    ],
    initialVitals: {
      heartRate: 135,
      systolicBP: 138,
      diastolicBP: 85,
      meanArterialPressure: 103,
      cardiacOutput: 7.5,
      strokeVolume: 56,
      svr: 1205,
      cvp: 10,
      spo2: 90,
      respiratoryRate: 18,
      paO2: 65,
      paCO2: 54,
      pfRatio: 260,
      ardsActive: true,
      ardsSeverityLevel: 'MILD',
      icp: 12,
      gcs: 13,
      pupilState: 'reactive',
      lactate: 3.5,
      pH: 7.24,
      hco3: 23.5,
      baseExcess: -2.8,
      temperature: 37.4,
      urineOutput: 0.6,
      creatinine: 1.1,
    },
    isVentilatorConnected: true,
    ventilatorPreset: {
      mode: 'VC-AC',
      fio2: 0.50,
      vt: 500,
      peep: 0,
      setRR: 10,
    },
    clinicalNotes: 'Hipercapnia permisiva (PaCO₂ hasta 80–100 mmHg) en status refractario para evitar barotrauma. FR baja (8–12 rpm) y VT moderado para prolongar tiempo espiratorio y reducir autoPEEP. PEEP extrínseco ≤ 80% del autoPEEP medido. Salbutamol + ipratropio nebulizados continuos en el circuito. Sulfato de magnesio 2g IV. Ketamina como broncodilatador en sedación (inhibe vagalmente el broncospasmo).',
    references: ['GINA 2024', 'Leatherman JW Crit Care 2009', 'Brenner B Ann Emerg Med 2009'],
  },

  {
    id: 'resp_epoc_no_infeccioso',
    category: 'respiratory',
    name: 'EPOC Agudizado — No Infeccioso',
    description: 'Exacerbación de EPOC Gold IV por exposición ambiental (humo). Hipercapnia aguda sobre crónica. PaCO₂ 68 mmHg. pH 7.26. Sin infiltrados en Rx. Retenedor crónico.',
    baseSeverity: 0.68,
    tags: ['EPOC', 'Hipercapnia', 'VNI', 'GOLD IV', 'Retención CO₂'],
    pathologyConfigs: [
      { domain: 'copd', subtype: 'exacerbacion_no_infecciosa', baseSeverity: 0.68 },
      { domain: 'ards', subtype: null,                         baseSeverity: 0.15 },
    ],
    initialVitals: {
      heartRate: 105,
      systolicBP: 148,
      diastolicBP: 88,
      meanArterialPressure: 108,
      cardiacOutput: 5.8,
      strokeVolume: 55,
      svr: 1425,
      cvp: 12,
      spo2: 84,
      respiratoryRate: 28,
      paO2: 55,
      paCO2: 68,
      pfRatio: 262,
      ardsActive: false,
      ardsSeverityLevel: 'NONE',
      icp: 12,
      gcs: 13,
      pupilState: 'reactive',
      lactate: 2.2,
      pH: 7.26,
      hco3: 30.5,
      baseExcess: 6.2,
      temperature: 37.0,
      urineOutput: 0.6,
      creatinine: 1.1,
    },
    isVentilatorConnected: false,
    recommendedRespSupport: 'hfnc',
    clinicalNotes: 'VNI como primera línea: reduce intubación, mortalidad y estancia UCI en EPOC (NNT ~10 para intubación). Objetivo SpO₂ 88–92% (evitar hiperoxi que worsens hipercapnia por mecanismo Haldane). Broncodilatadores + corticoides sistémicos 5 días. Intubación si falla VNI, encefalopatía o parada respiratoria inminente. PaCO₂ crónica estimada por bicarbonato basal.',
    references: ['GOLD 2024', 'Ram FS Cochrane 2004', 'Wedzicha JA ERJ 2017'],
  },

  {
    id: 'resp_epoc_infeccioso',
    category: 'respiratory',
    name: 'EPOC Agudizado — Infeccioso (Neumonía)',
    description: 'Exacerbación infecciosa EPOC GOLD III por Haemophilus influenzae. Neumonía lobar derecha. Purulencia, hipercapnia y sepsis. Requiere intubación por fallo VNI.',
    baseSeverity: 0.78,
    tags: ['EPOC', 'Neumonía', 'Haemophilus', 'Intubación', 'Sepsis'],
    pathologyConfigs: [
      { domain: 'copd',      subtype: 'exacerbacion_infecciosa', baseSeverity: 0.78 },
      { domain: 'pneumonia', subtype: 'bacteriana',               baseSeverity: 0.65 },
      { domain: 'sepsis',    subtype: null,                       baseSeverity: 0.40 },
      { domain: 'ards',      subtype: null,                       baseSeverity: 0.35 },
    ],
    initialVitals: {
      heartRate: 110,
      systolicBP: 108,
      diastolicBP: 65,
      meanArterialPressure: 79,
      cardiacOutput: 6.2,
      strokeVolume: 56,
      svr: 1104,
      cvp: 10,
      spo2: 86,
      respiratoryRate: 30,
      paO2: 60,
      paCO2: 62,
      pfRatio: 200,
      ardsActive: true,
      ardsSeverityLevel: 'MODERATE',
      icp: 12,
      gcs: 13,
      pupilState: 'reactive',
      lactate: 3.0,
      pH: 7.22,
      hco3: 25.5,
      baseExcess: -0.8,
      temperature: 38.5,
      urineOutput: 0.5,
      creatinine: 1.3,
    },
    isVentilatorConnected: true,
    ventilatorPreset: {
      mode: 'VC-AC',
      fio2: 0.50,
      vt: 480,
      peep: 5,
      setRR: 12,
    },
    initialModifiers: {
      svrMultiplier: 0.80,
      capillaryLeakRate: 4.0,
      hyperdynamicFactor: 1.12,
      lungShuntFraction: 0.32,
      complianceMultiplier: 0.58,
    },
    clinicalNotes: 'EPOC intubado: FR baja (10–14) y VT sin exceder Pplat 30 cmH₂O para evitar hiperinflación dinámica. Medir autoPEEP con pausa espiratoria. ATB: amoxicilina-clavulánico o fluoroquinolona. Desescalada precoz para evitar resistencias. Weaning difícil por hiperinflación y debilidad muscular: SBT cortos, tolerancia a hipercapnia permisiva durante weaning.',
    references: ['GOLD 2024', 'Wedzicha JA ERJ 2017', 'Anzueto A Crit Care Med 2010'],
  },
];
