import type { ScenarioDefinition } from '../store/useScenarioStore';

// Valores MAP: (SBP + 2×DBP) / 3
// SVR = (MAP − CVP) × 79.9 / CO  [dyn·s·cm⁻⁵]
// Referencia primaria: SSC 2021 (Evans L et al., Intensive Care Med)

export const sepsisScenarios: ScenarioDefinition[] = [
  {
    id: 'sepsis_shock_pulmonar',
    category: 'sepsis',
    name: 'Shock Séptico — Foco Pulmonar',
    description: 'Neumonía grave por S. pneumoniae con progresión a shock séptico y SDRA moderado. SpO₂ 90% con mascarilla al 60%. Lactato 4.2.',
    baseSeverity: 0.75,
    tags: ['Shock', 'Sepsis', 'Neumonía', 'SDRA', 'CURB-65'],
    pathologyConfigs: [
      { domain: 'sepsis',    subtype: null,          baseSeverity: 0.70 },
      { domain: 'ards',      subtype: null,          baseSeverity: 0.58 },
      { domain: 'pneumonia', subtype: 'bacteriana',  baseSeverity: 0.75 },
    ],
    initialVitals: {
      heartRate: 118,
      systolicBP: 85,
      diastolicBP: 50,
      meanArterialPressure: 62,
      cardiacOutput: 7.2,
      strokeVolume: 61,
      svr: 644,
      cvp: 4,
      spo2: 90,
      respiratoryRate: 28,
      paO2: 62,
      paCO2: 33,
      pfRatio: 103,
      ardsActive: true,
      ardsSeverityLevel: 'SEVERE',
      icp: 12,
      gcs: 13,
      pupilState: 'reactive',
      lactate: 4.2,
      pH: 7.26,
      hco3: 18.5,
      baseExcess: -7.2,
      temperature: 39.2,
      urineOutput: 0.3,
      creatinine: 1.9,
    },
    isVentilatorConnected: true,
    ventilatorPreset: {
      mode: 'VC-AC',
      fio2: 0.70,
      vt: 420,
      peep: 10,
      setRR: 20,
    },
    initialModifiers: {
      svrMultiplier: 0.58,
      capillaryLeakRate: 7.0,
      hyperdynamicFactor: 1.28,
      lungShuntFraction: 0.40,
      complianceMultiplier: 0.55,
    },
    clinicalNotes: 'Bundle hora-1 SSC 2021: lactato, hemocultivos ×2, ATB de amplio espectro, resucitación con cristaloides 30 mL/kg si MAP < 65 o lactato > 4. Noradrenalina si refractario. Objetivo MAP ≥ 65 mmHg. Ventilación protectora: VT 6 mL/kg PBW, ΔP < 15 cmH₂O, PEEP ≥ 8. Prone si P/F < 150 con PEEP ≥ 5.',
    references: ['Evans L ICM 2021', 'Berlin JAMA 2012', 'Guérin NEJM 2013'],
  },

  {
    id: 'sepsis_shock_abdominal',
    category: 'sepsis',
    name: 'Shock Séptico — Foco Abdominal',
    description: 'Perforación de colon sigmoides. Peritonitis fecal generalizada. Shock séptico con disfunción multiorgánica incipiente. Lactato 5.5.',
    baseSeverity: 0.80,
    tags: ['Shock', 'Peritonitis', 'Cirugía', 'Laparotomía', 'MOF'],
    pathologyConfigs: [
      { domain: 'sepsis', subtype: null, baseSeverity: 0.78 },
      { domain: 'ards',   subtype: null, baseSeverity: 0.35 },
    ],
    initialVitals: {
      heartRate: 124,
      systolicBP: 80,
      diastolicBP: 48,
      meanArterialPressure: 59,
      cardiacOutput: 7.8,
      strokeVolume: 63,
      svr: 580,
      cvp: 3,
      spo2: 94,
      respiratoryRate: 26,
      paO2: 78,
      paCO2: 31,
      pfRatio: 260,
      ardsActive: true,
      ardsSeverityLevel: 'MILD',
      icp: 12,
      gcs: 13,
      pupilState: 'reactive',
      lactate: 5.5,
      pH: 7.22,
      hco3: 16.0,
      baseExcess: -10.2,
      temperature: 38.8,
      urineOutput: 0.2,
      creatinine: 2.4,
    },
    isVentilatorConnected: true,
    ventilatorPreset: {
      mode: 'VC-AC',
      fio2: 0.60,
      vt: 420,
      peep: 8,
      setRR: 18,
    },
    initialModifiers: {
      svrMultiplier: 0.52,
      capillaryLeakRate: 8.5,
      hyperdynamicFactor: 1.30,
      lungShuntFraction: 0.22,
      complianceMultiplier: 0.72,
    },
    clinicalNotes: 'Control de foco quirúrgico urgente: pilar fundamental del manejo. Reanimación + cirugía simultáneas si inestable. Piperacilina-tazobactam ± metronidazol. Vitamina C + tiamina controvertido pero frecuente. Vasopresina segunda línea. Abdomen abierto con VAC en peritonitis grave para reinspección a 48h.',
    references: ['SSC Evans 2021', 'Sartelli WSES 2020', 'Marik PE CCM 2017'],
  },

  {
    id: 'sepsis_shock_urinario',
    category: 'sepsis',
    name: 'Shock Séptico — Foco Urinario',
    description: 'Pielonefritis obstructiva por cálculo ureteral derecho. E. coli BLEE. Urosepsis con shock distributivo y AKI estadio 2.',
    baseSeverity: 0.68,
    tags: ['Urosepsis', 'Pielonefritis', 'BLEE', 'AKI', 'Nefrostomía'],
    pathologyConfigs: [
      { domain: 'sepsis', subtype: null, baseSeverity: 0.62 },
    ],
    initialVitals: {
      heartRate: 112,
      systolicBP: 90,
      diastolicBP: 55,
      meanArterialPressure: 67,
      cardiacOutput: 6.5,
      strokeVolume: 58,
      svr: 780,
      cvp: 4,
      spo2: 95,
      respiratoryRate: 22,
      paO2: 82,
      paCO2: 35,
      pfRatio: 391,
      ardsActive: false,
      ardsSeverityLevel: 'NONE',
      icp: 12,
      gcs: 13,
      pupilState: 'reactive',
      lactate: 3.2,
      pH: 7.30,
      hco3: 20.0,
      baseExcess: -5.0,
      temperature: 38.6,
      urineOutput: 0.2,
      creatinine: 2.8,
    },
    isVentilatorConnected: false,
    recommendedRespSupport: 'nasal_cannula',
    initialModifiers: {
      svrMultiplier: 0.68,
      capillaryLeakRate: 5.5,
      hyperdynamicFactor: 1.22,
      lungShuntFraction: 0.08,
      complianceMultiplier: 0.95,
    },
    clinicalNotes: 'Drenaje urgente del foco obstructivo: nefrostomía percutánea o stent ureteral. ATB empírico: carbapenem ante sospecha BLEE (fosfomicina alternativa). Objetivo diuresis > 0.5 mL/kg/h. Diálisis si AKI estadio 3 + sobrecarga de volumen / hiperpotasemia / acidosis refractaria. Pronóstico bueno si control de foco precoz.',
    references: ['SSC Evans 2021', 'IDSA UTI Guidelines 2011', 'KDIGO AKI 2012'],
  },

  {
    id: 'sepsis_polimicrobiana_3focos',
    category: 'sepsis',
    name: 'Sepsis Polimicrobiana (3 Focos)',
    description: 'Bacteriemia por CVC + neumonía ventilador-asociada + foco abdominal tras cirugía de urgencia. Lactato 7.8. MOF establecido.',
    baseSeverity: 0.92,
    tags: ['MOF', 'Polimicrobiana', 'Nosocomial', 'APACHE-II', 'Prognosis'],
    pathologyConfigs: [
      { domain: 'sepsis',    subtype: null,         baseSeverity: 0.90 },
      { domain: 'ards',      subtype: null,         baseSeverity: 0.72 },
      { domain: 'pneumonia', subtype: 'bacteriana', baseSeverity: 0.80 },
    ],
    initialVitals: {
      heartRate: 132,
      systolicBP: 75,
      diastolicBP: 42,
      meanArterialPressure: 53,
      cardiacOutput: 8.2,
      strokeVolume: 62,
      svr: 480,
      cvp: 3,
      spo2: 88,
      respiratoryRate: 30,
      paO2: 58,
      paCO2: 30,
      pfRatio: 83,
      ardsActive: true,
      ardsSeverityLevel: 'SEVERE',
      icp: 12,
      gcs: 11,
      pupilState: 'reactive',
      lactate: 7.8,
      pH: 7.18,
      hco3: 13.5,
      baseExcess: -13.2,
      temperature: 40.1,
      urineOutput: 0.1,
      creatinine: 3.5,
    },
    isVentilatorConnected: true,
    ventilatorPreset: {
      mode: 'VC-AC',
      fio2: 0.80,
      vt: 420,
      peep: 12,
      setRR: 22,
    },
    initialModifiers: {
      svrMultiplier: 0.44,
      capillaryLeakRate: 9.5,
      hyperdynamicFactor: 1.38,
      lungShuntFraction: 0.55,
      complianceMultiplier: 0.38,
    },
    clinicalNotes: 'SOFA > 11 asociado a mortalidad > 50%. ATB de amplio espectro: carbapenem + vancomicina + fluconazol. Considerar inmunoglobulinas IV en shock refractario. Hidrocortisona si refractario a vasopresores. Prone + bloqueo neuromuscular si P/F < 100. Hemodiálisis venovenosa continua (CRRT) si AKI estadio 3.',
    references: ['SSC Evans 2021', 'Annane NEJM 2018 (hidrocortisona)', 'Papazian NEJM 2010 (BNM)'],
  },

  {
    id: 'sepsis_shock_toxico',
    category: 'sepsis',
    name: 'Shock Tóxico Estafilocócico',
    description: 'Síndrome de shock tóxico por S. aureus. Exantema difuso, descamación palmoplantar, fiebre 41°C. Lactato 9.2. Shock refractario.',
    baseSeverity: 0.95,
    tags: ['STT', 'Staphylococcus', 'Exotoxina', 'TSST-1', 'Shock refractario'],
    pathologyConfigs: [
      { domain: 'sepsis', subtype: null, baseSeverity: 0.95 },
      { domain: 'ards',   subtype: null, baseSeverity: 0.60 },
    ],
    initialVitals: {
      heartRate: 142,
      systolicBP: 70,
      diastolicBP: 38,
      meanArterialPressure: 49,
      cardiacOutput: 9.5,
      strokeVolume: 67,
      svr: 372,
      cvp: 2,
      spo2: 86,
      respiratoryRate: 32,
      paO2: 55,
      paCO2: 29,
      pfRatio: 92,
      ardsActive: true,
      ardsSeverityLevel: 'SEVERE',
      icp: 12,
      gcs: 10,
      pupilState: 'reactive',
      lactate: 9.2,
      pH: 7.12,
      hco3: 11.5,
      baseExcess: -15.8,
      temperature: 40.8,
      urineOutput: 0.1,
      creatinine: 3.2,
    },
    isVentilatorConnected: true,
    ventilatorPreset: {
      mode: 'VC-AC',
      fio2: 0.80,
      vt: 420,
      peep: 10,
      setRR: 22,
    },
    initialModifiers: {
      svrMultiplier: 0.40,
      capillaryLeakRate: 10.0,
      hyperdynamicFactor: 1.40,
      lungShuntFraction: 0.50,
      complianceMultiplier: 0.45,
    },
    clinicalNotes: 'Eliminación del foco (desbridamiento, drenaje). Flucloxacilina/cefazolina + clindamicina (inhibe producción de toxinas). Clindamicina es clave por efecto antitoxina. IgIV 1–2 g/kg en shock refractario (evidencia moderada). Corticoides contraindicados en STT clásico. Noradrenalina + vasopresina + adrenalina pueden necesitarse en cadena.',
    references: ['Stevens DL NEJM 2000', 'Parks T Lancet 2020', 'IDSA SST Guidelines 2014'],
  },
];
