// src/scenarios/surgicalAbdominalScenarios.ts
//
// Escenarios quirúrgicos críticos abdominales.
// Refs: Solomkin JS et al. CID 2010; Mazuski JE Surg Infect 2017;
//       WSES Guidelines peritonitis 2021; SSC 2021 (Rhodes ICM 2017).

import type { ScenarioDefinition } from '../store/useScenarioStore';

export const surgicalAbdominalScenarios: ScenarioDefinition[] = [
  {
    id: 'surg_peritonitis_fecal',
    category: 'surgical',
    name: 'Peritonitis Fecaloidea PO',
    description: 'PO 1 de resección sigmoidea de urgencia por diverticulitis perforada. Peritonitis fecaloidea generalizada con lavado. Drenes activos. Sepsis abdominal persistente.',
    baseSeverity: 0.80,
    tags: ['Peritonitis', 'Fecaloidea', 'Sepsis', 'Postoperatorio', 'Dren'],
    surgicalDrainStatus: 'purulent',
    pathologyConfigs: [
      { domain: 'sepsis',   subtype: 'abdominal',     baseSeverity: 0.78 },
      { domain: 'sepsis',   subtype: 'aki_prerenal',  baseSeverity: 0.50 },
    ],
    initialVitals: {
      heartRate: 118, systolicBP: 88, diastolicBP: 52,
      meanArterialPressure: 64, cardiacOutput: 6.8, strokeVolume: 58,
      svr: 690, cvp: 4,
      spo2: 95, respiratoryRate: 26,
      paO2: 68, paCO2: 32, pfRatio: 194,
      ardsActive: false, ardsSeverityLevel: 'NONE',
      lactate: 3.8, pH: 7.28, hco3: 18.0, baseExcess: -8.0,
      temperature: 38.9, creatinine: 1.8, urineOutput: 0.3,
      icp: 10, gcs: 14, pupilState: 'reactive',
    },
    clinicalNotes: 'Paciente con peritonitis fecaloidea generalizada, 3 drenes en sitio. Cultivos pendientes. Candida en Gram. Requiere 2.ª revisión quirúrgica si no mejora en 48h.',
    references: [
      'Solomkin JS et al. CID 2010;50:133 — diagnóstico y terapia infección intraabdominal',
      'WSES IAI Guidelines 2021 — peritonitis fecaloidea',
    ],
  },
  {
    id: 'surg_necrotizing_pancreatitis',
    category: 'surgical',
    name: 'Pancreatitis Necrotizante PO',
    description: 'PO 5 de pancreatitis aguda necrotizante biliar. Drenaje retropancreático con débito hemático. SIRS persistente, inicio de SDRA moderado.',
    baseSeverity: 0.85,
    tags: ['Pancreatitis', 'Necrotizante', 'SDRA', 'Drain', 'Sepsis'],
    surgicalDrainStatus: 'serosanguinolent',
    pathologyConfigs: [
      { domain: 'sepsis',       subtype: 'abdominal',     baseSeverity: 0.70 },
      { domain: 'ards',         subtype: 'moderate',      baseSeverity: 0.60 },
      { domain: 'sepsis',       subtype: 'aki_prerenal',  baseSeverity: 0.55 },
    ],
    initialVitals: {
      heartRate: 124, systolicBP: 96, diastolicBP: 60,
      meanArterialPressure: 72, cardiacOutput: 7.2, strokeVolume: 58,
      svr: 720, cvp: 6,
      spo2: 88, respiratoryRate: 28,
      paO2: 56, paCO2: 38, pfRatio: 150,
      ardsActive: true, ardsSeverityLevel: 'MODERATE',
      lactate: 2.9, pH: 7.32, hco3: 19.0, baseExcess: -6.0,
      temperature: 39.2, creatinine: 2.1, urineOutput: 0.25,
      icp: 10, gcs: 13, pupilState: 'reactive',
    },
    recommendedRespSupport: 'arm',
    isVentilatorConnected: true,
    ventilatorPreset: { fio2: 0.60, peep: 10, vt: 380, setRR: 18, mode: 'VC-AC' },
    clinicalNotes: 'Necrosis pancreática 60%. Cultivo de bilis: E. coli + Enterococcus faecalis. Dren retropancreático con débito 200 mL/h hemático. Indicar nutrición enteral transpilórica si tolera.',
    references: [
      'Tenner S et al. Am J Gastroenterol 2013;108:1400 — guías pancreatitis aguda',
      'Banks PA et al. Gut 2013;62:102 — clasificación revisada Atlanta 2012',
    ],
  },
  {
    id: 'surg_whipple_complicado',
    category: 'surgical',
    name: 'Whipple Complicado PO',
    description: 'PO 4 de duodenopancreatectomía cefálica (Whipple). Fuga anastomótica biliar + íleo prolongado. Dren biliar con débito purulento.',
    baseSeverity: 0.75,
    tags: ['Whipple', 'Duodenopancreatectomía', 'Fuga Biliar', 'Sepsis'],
    surgicalDrainStatus: 'high_output',
    pathologyConfigs: [
      { domain: 'sepsis',   subtype: 'abdominal',    baseSeverity: 0.65 },
      { domain: 'sepsis',   subtype: 'cholestasis',  baseSeverity: 0.40 },
    ],
    initialVitals: {
      heartRate: 106, systolicBP: 100, diastolicBP: 62,
      meanArterialPressure: 75, cardiacOutput: 6.0, strokeVolume: 57,
      svr: 900, cvp: 7,
      spo2: 94, respiratoryRate: 22,
      paO2: 75, paCO2: 36, pfRatio: 230,
      ardsActive: false, ardsSeverityLevel: 'NONE',
      lactate: 2.1, pH: 7.34, hco3: 20.0, baseExcess: -5.0,
      temperature: 38.7, creatinine: 1.4, urineOutput: 0.45,
      icp: 10, gcs: 15, pupilState: 'reactive',
    },
    clinicalNotes: 'Fuga grado B (ISGPS). Dren con débito bilioso 300 mL/d → cultivo pendiente. Bilirubina directa 8.2 mg/dL. Iniciar ATB anti-gram(-) y anaerobios.',
    references: [
      'Bassi C et al. Surgery 2005;138:8 — ISGPS fistula pancreática',
      'Koch M et al. Surgery 2011;149:680 — fuga biliar pos-Whipple',
    ],
  },
  {
    id: 'surg_anastomosis_precaria',
    category: 'surgical',
    name: 'Anastomosis Precaria PO',
    description: 'PO 3 de hemicolectomía derecha. Dren con cambio de aspecto a contenido fecaloide. Signos incipientes de fuga anastomótica.',
    baseSeverity: 0.70,
    tags: ['Anastomosis', 'Fuga', 'Colectomía', 'Peritonitis'],
    surgicalDrainStatus: 'serosanguinolent',
    pathologyConfigs: [
      { domain: 'sepsis',   subtype: 'abdominal',    baseSeverity: 0.60 },
    ],
    initialVitals: {
      heartRate: 102, systolicBP: 105, diastolicBP: 65,
      meanArterialPressure: 78, cardiacOutput: 5.8, strokeVolume: 57,
      svr: 980, cvp: 7,
      spo2: 96, respiratoryRate: 20,
      paO2: 82, paCO2: 38, pfRatio: 290,
      ardsActive: false, ardsSeverityLevel: 'NONE',
      lactate: 1.9, pH: 7.35, hco3: 21.5, baseExcess: -3.0,
      temperature: 38.4, creatinine: 1.1, urineOutput: 0.65,
      icp: 10, gcs: 15, pupilState: 'reactive',
    },
    clinicalNotes: 'Dren con contenido turbio creciente. TAC abdomen: colección perianastomótica 4 cm. Valorar re-exploración vs. drenaje percutáneo radiológico.',
    references: [
      'Hyman N et al. Ann Surg 2007;245:254 — dehiscencia anastomótica colónica',
    ],
  },
  {
    id: 'surg_dren_retirado',
    category: 'surgical',
    name: 'Dren Retirado Precozmente',
    description: 'PO 2 de colecistectomía laparoscópica complicada. Dren retirado a las 24h. Nuevo dolor abdominal, fiebre, bilis libre en cavidad.',
    baseSeverity: 0.68,
    tags: ['Biloma', 'Fuga Biliar', 'Laparoscopía', 'Colecistectomía'],
    surgicalDrainStatus: 'recently_removed',
    pathologyConfigs: [
      { domain: 'sepsis',   subtype: 'abdominal',    baseSeverity: 0.55 },
    ],
    initialVitals: {
      heartRate: 98, systolicBP: 112, diastolicBP: 70,
      meanArterialPressure: 84, cardiacOutput: 5.5, strokeVolume: 56,
      svr: 1100, cvp: 7,
      spo2: 97, respiratoryRate: 18,
      paO2: 88, paCO2: 39, pfRatio: 338,
      ardsActive: false, ardsSeverityLevel: 'NONE',
      lactate: 1.5, pH: 7.37, hco3: 22.5, baseExcess: -1.8,
      temperature: 38.2, creatinine: 0.9, urineOutput: 0.9,
      icp: 10, gcs: 15, pupilState: 'reactive',
    },
    clinicalNotes: 'Biloma post-laparoscopía. CPRE + stent biliar posiblemente indicado. Reintroducir dren bajo eco. ATB ampicilina-sulbactam.',
    references: [
      'Sicklick JK et al. Ann Surg 2005;241:786 — lesión vía biliar',
    ],
  },
  {
    id: 'surg_variceal_tips',
    category: 'surgical',
    name: 'HDA Variceal Post-TIPS',
    description: 'Cirrosis Child C, hemorragia variceal masiva tratada con TIPS emergente. PO 1. Encefalopatía hepática grado II en desarrollo.',
    baseSeverity: 0.88,
    tags: ['TIPS', 'Várices', 'Cirrosis', 'Encefalopatía', 'Hemorragia'],
    surgicalDrainStatus: 'none',
    pathologyConfigs: [
      { domain: 'sepsis',   subtype: 'cirrhosis',    baseSeverity: 0.85 },
      { domain: 'sepsis',   subtype: 'hrs_type1',    baseSeverity: 0.60 },
    ],
    initialVitals: {
      heartRate: 114, systolicBP: 92, diastolicBP: 58,
      meanArterialPressure: 69, cardiacOutput: 7.8, strokeVolume: 68,
      svr: 620, cvp: 5,
      spo2: 93, respiratoryRate: 24,
      paO2: 62, paCO2: 33, pfRatio: 188,
      ardsActive: false, ardsSeverityLevel: 'NONE',
      lactate: 4.2, pH: 7.30, hco3: 16.0, baseExcess: -10.0,
      temperature: 37.4, creatinine: 2.4, urineOutput: 0.2,
      icp: 10, gcs: 12, pupilState: 'reactive',
    },
    initialBloodVolumeMl: 3800,
    clinicalNotes: 'Hb 7.2 tras resucitación 6U GRE + 4U PFC. Protocolo 1:1:1 activo. NH4+ = 118 mcmol/L. Iniciar lactulosa. Vigilar síndrome hepatorrenal.',
    references: [
      'García-Pagán JC et al. NEJM 2010;362:2370 — TIPS en HDA variceal',
      'Baveno VII 2022 — consenso hipertensión portal',
    ],
  },
  {
    id: 'surg_isquemia_mesenterica',
    category: 'surgical',
    name: 'Isquemia Mesentérica PO',
    description: 'PO de resección intestinal extensa (90 cm yeyuno) por isquemia mesentérica. Intestino corto funcional. Síndrome de reperfusión.',
    baseSeverity: 0.90,
    tags: ['Isquemia', 'Mesentérica', 'Intestino Corto', 'Reperfusión'],
    surgicalDrainStatus: 'in_situ',
    pathologyConfigs: [
      { domain: 'cardio',   subtype: 'low_output',   baseSeverity: 0.70 },
      { domain: 'sepsis',   subtype: 'aki_prerenal', baseSeverity: 0.65 },
      { domain: 'sepsis',         subtype: 'abdominal',    baseSeverity: 0.60 },
    ],
    initialVitals: {
      heartRate: 128, systolicBP: 82, diastolicBP: 48,
      meanArterialPressure: 59, cardiacOutput: 5.2, strokeVolume: 41,
      svr: 790, cvp: 3,
      spo2: 91, respiratoryRate: 30,
      paO2: 52, paCO2: 30, pfRatio: 141,
      ardsActive: false, ardsSeverityLevel: 'NONE',
      lactate: 6.8, pH: 7.18, hco3: 12.0, baseExcess: -14.0,
      temperature: 36.8, creatinine: 2.8, urineOutput: 0.1,
      icp: 10, gcs: 13, pupilState: 'reactive',
    },
    initialBloodVolumeMl: 3600,
    recommendedRespSupport: 'arm',
    isVentilatorConnected: true,
    ventilatorPreset: { fio2: 0.70, peep: 8, vt: 400, setRR: 20, mode: 'VC-AC' },
    clinicalNotes: 'Lactato 6.8 → iniciar target de aclaramiento. Protocolo resucitación 60 mL/kg. Nutrición parenteral total. Segunda cirugía en 48h ("second look").',
    references: [
      'Schoots IG et al. Ann Surg 2004;240:65 — isquemia mesentérica aguda',
      'Tilsed JVT et al. EJVES 2016;51:739 — guías ESVS isquemia mesentérica',
    ],
  },
  {
    id: 'surg_compartimental_abdominal',
    category: 'surgical',
    name: 'Síndrome Compartimental Abdominal',
    description: 'Presión intraabdominal 28 cmH₂O tras resucitación masiva (18 L cristaloides). Oligoanuria, ventilación dificultosa. Requiere laparostomía descompresiva.',
    baseSeverity: 0.92,
    tags: ['SCA', 'Hipertensión Intraabdominal', 'Laparostomía', 'MOF'],
    surgicalDrainStatus: 'none',
    pathologyConfigs: [
      { domain: 'sepsis',   subtype: 'aki_anuric', baseSeverity: 0.80 },
      { domain: 'ards',     subtype: 'severe',     baseSeverity: 0.70 },
      { domain: 'cardio',   subtype: 'low_output', baseSeverity: 0.65 },
    ],
    initialVitals: {
      heartRate: 132, systolicBP: 78, diastolicBP: 44,
      meanArterialPressure: 55, cardiacOutput: 4.2, strokeVolume: 32,
      svr: 960, cvp: 18,
      spo2: 86, respiratoryRate: 32,
      paO2: 48, paCO2: 52, pfRatio: 110,
      ardsActive: true, ardsSeverityLevel: 'SEVERE',
      lactate: 7.5, pH: 7.14, hco3: 10.5, baseExcess: -16.0,
      temperature: 36.2, creatinine: 3.6, urineOutput: 0.05,
      icp: 10, gcs: 10, pupilState: 'sluggish',
    },
    initialBloodVolumeMl: 6800,
    recommendedRespSupport: 'arm',
    isVentilatorConnected: true,
    ventilatorPreset: { fio2: 0.90, peep: 14, vt: 360, setRR: 22, mode: 'VC-AC' },
    clinicalNotes: 'PIA > 20 + fallo orgánico → SCA grado IV (WSACS). Indicación laparostomía de urgencia. Hemofiltración continua para "desescalar" sobrecarga hídrica.',
    references: [
      'Kirkpatrick AW et al. ICM 2013;39:1190 — WSACS consenso SCA',
      'Reintam Blaser A et al. ICM 2012;38:1594 — hipertensión intraabdominal UCI',
    ],
  },
];
