// src/scenarios/neuro/index.ts — 13 neurocritical scenarios
import type { ScenarioDefinition } from '../../store/useScenarioStore';

export const neuroExtScenarios: ScenarioDefinition[] = [
  // ── TBI Severe GCS 6 ────────────────────────────────────────────────────────
  {
    id: 'tbi_severe_gcs6',
    category: 'neuro',
    name: 'TBI Grave — GCS 6 + Hipertensión IC',
    description: 'TCE grave por accidente automovilístico. GCS 6 (E1V1M4). TC: contusión temporal derecha + edema difuso. PIC elevada estimada. Indicación catéter PIC BTF clase IIB.',
    baseSeverity: 0.82,
    tags: ['TCE', 'TBI', 'PIC', 'Hipertensión IC', 'ARM'],
    pathologyConfigs: [
      { domain: 'neuroCritical', subtype: 'tbi', baseSeverity: 0.82 },
    ],
    initialVitals: { heartRate: 54, systolicBP: 172, diastolicBP: 98, meanArterialPressure: 123, gcs: 6, icp: 28, pupilState: 'sluggish', temperature: 37.8, respiratoryRate: 10, spo2: 96, lactate: 2.1 },
    isVentilatorConnected: true,
    ventilatorPreset: { fio2: 0.45, peep: 5, vt: 480, setRR: 14 },
    icpCatheterRequired: true,
    clinicalNotes: 'Tríada de Cushing parcial (HTA + bradicardia). Riesgo herniation. Osmoterapia, posición 30°, hipocapnia controlada (pCO2 35-38).',
    references: ['Hawryluk GWJ et al. ICM 2022;48:649-66', 'BTF Guidelines 4th ed 2016'],
  },
  // ── TBI Moderate GCS 9 ─────────────────────────────────────────────────────
  {
    id: 'tbi_moderate_gcs9',
    category: 'neuro',
    name: 'TBI Moderado — GCS 9',
    description: 'TCE moderado tras caída en altura de 4 metros. GCS 9 (E2V3M4). TC: pequeña contusión parietal, sin efecto de masa. Sin indicación actual de PIC.',
    baseSeverity: 0.52,
    tags: ['TCE', 'TBI', 'Monitoreo', 'Caída'],
    pathologyConfigs: [
      { domain: 'neuroCritical', subtype: 'tbi', baseSeverity: 0.50 },
    ],
    initialVitals: { heartRate: 88, systolicBP: 148, diastolicBP: 82, meanArterialPressure: 104, gcs: 9, temperature: 37.0, respiratoryRate: 18, spo2: 97 },
    isVentilatorConnected: false,
    icpCatheterRequired: false,
    clinicalNotes: 'Monitoreo neurológico seriado. TC control a las 6h. Objetivo MAP ≥ 80 mmHg (PPC ≥ 60). Evitar hipotensión e hipoxemia.',
    references: ['Carney N et al. Neurosurgery 2017 (BTF)'],
  },
  // ── SAH Fisher IV ───────────────────────────────────────────────────────────
  {
    id: 'sah_fisher_iv',
    category: 'neuro',
    name: 'HSA Aneurismática — Fisher IV',
    description: 'Hemorragia subaracnoidea aneurismática (WFNS IV, Fisher IV) por rotura de aneurisma de comunicante anterior. Riesgo de resangrado y vasoespasmo. PIC elevada.',
    baseSeverity: 0.88,
    tags: ['HSA', 'Aneurisma', 'Vasoespasmo', 'PIC', 'ARM'],
    pathologyConfigs: [
      { domain: 'neuroCritical', subtype: 'sah', baseSeverity: 0.88 },
    ],
    initialVitals: { heartRate: 92, systolicBP: 188, diastolicBP: 108, meanArterialPressure: 135, gcs: 7, icp: 22, temperature: 38.1, spo2: 95, lactate: 2.4 },
    isVentilatorConnected: true,
    ventilatorPreset: { fio2: 0.50, peep: 6, vt: 460 },
    icpCatheterRequired: true,
    clinicalNotes: 'Nimodipino 60mg c/4h profilaxis vasoespasmo. Control HTA (SBP < 160 hasta clipeo). TC-angio urgente.',
    references: ['Robba C et al. Lancet Neurol 2021 (SYNAPSE-ICU)', 'Connolly ES Stroke 2012'],
  },
  // ── ICH Thalamic ────────────────────────────────────────────────────────────
  {
    id: 'ich_thalamic',
    category: 'neuro',
    name: 'HIC Talámico — HTA Severa',
    description: 'Hemorragia intracraneana találmica derecha (18 mL). HTA severa no controlada. GCS 10. Sin extensión ventricular. No indicación quirúrgica inicial.',
    baseSeverity: 0.65,
    tags: ['HIC', 'Hemorragia', 'Tálamo', 'HTA'],
    pathologyConfigs: [
      { domain: 'neuroCritical', subtype: 'ich', baseSeverity: 0.65 },
    ],
    initialVitals: { heartRate: 72, systolicBP: 210, diastolicBP: 120, meanArterialPressure: 150, gcs: 10, temperature: 37.0, spo2: 97 },
    isVentilatorConnected: false,
    icpCatheterRequired: false,
    clinicalNotes: 'Control HTA: SBP < 140 mmHg en 1h (INTERACT2). Evitar hipotensión. TC control a 6h para descartar expansión.',
    references: ['Anderson CS (INTERACT2) NEJM 2013', 'Qureshi AI Neurology 2016'],
  },
  // ── ICH Brainstem ───────────────────────────────────────────────────────────
  {
    id: 'ich_brainstem',
    category: 'neuro',
    name: 'HIC Troncoencefálico — Pontino',
    description: 'Hemorragia pontina masiva (8 mL) en paciente hipertenso. GCS 5, pinpoint pupils, tetraparesia, patrón respiratorio atáxico. Pronóstico reservado.',
    baseSeverity: 0.94,
    tags: ['HIC', 'Tronco', 'Pons', 'GCS Bajo', 'ARM'],
    pathologyConfigs: [
      { domain: 'neuroCritical', subtype: 'ich_brainstem', baseSeverity: 0.94 },
    ],
    initialVitals: { heartRate: 48, systolicBP: 190, diastolicBP: 115, meanArterialPressure: 140, gcs: 5, pupilState: 'miotic', temperature: 37.5, respiratoryRate: 6, spo2: 88 },
    isVentilatorConnected: true,
    ventilatorPreset: { fio2: 0.80, peep: 8 },
    icpCatheterRequired: false,
    clinicalNotes: 'Soporte ventilatorio obligatorio. Considerar limitación de esfuerzo terapéutico en reunión familiar. Sin indicación quirúrgica.',
    references: ['Hemphill JC Stroke 2015 (AHA/ASA Guidelines)'],
  },
  // ── Status Epilepticus Refractory ───────────────────────────────────────────
  {
    id: 'status_epilepticus_refractory',
    category: 'neuro',
    name: 'Estado Epiléptico Refractario',
    description: 'Estado epiléptico refractario a BZD y fenitoína por más de 30 minutos. En anestesia barbitúrica. GCS 6 bajo sedación profunda. Monitoreo EEG continuo.',
    baseSeverity: 0.78,
    tags: ['Epilepsia', 'Estado Epiléptico', 'ARM', 'Anestesia'],
    pathologyConfigs: [
      { domain: 'neuroCritical', subtype: 'status_epilepticus', baseSeverity: 0.78 },
    ],
    initialVitals: { heartRate: 115, systolicBP: 145, diastolicBP: 85, meanArterialPressure: 105, gcs: 6, temperature: 38.5, lactate: 3.8 },
    isVentilatorConnected: true,
    ventilatorPreset: { fio2: 0.50, peep: 5 },
    clinicalNotes: 'Propofol + midazolam en infusión. Ketamina como tercera línea. Corrección hiponatremia si presente. Búsqueda etiológica (LCR, TC, autoinmune).',
    references: ['Brophy GM Neurocrit Care 2012', 'Kapur J NEJM 2019 (ESETT)'],
  },
  // ── Bacterial Meningitis with ICH ───────────────────────────────────────────
  {
    id: 'bacterial_meningitis_ich',
    category: 'neuro',
    name: 'Meningitis Bacteriana + HIC Secundaria',
    description: 'Meningitis bacteriana por N. meningitidis con hidrocefalia aguda y PIC elevada. GCS 8. Petequias en piel. LCR purulento. Inicio empírico urgente.',
    baseSeverity: 0.86,
    tags: ['Meningitis', 'Meningococo', 'LCR', 'PIC', 'ARM'],
    pathologyConfigs: [
      { domain: 'neuroCritical', subtype: 'meningitis', baseSeverity: 0.82 },
      { domain: 'sepsis', subtype: null, baseSeverity: 0.70 },
    ],
    initialVitals: { heartRate: 128, systolicBP: 92, diastolicBP: 58, meanArterialPressure: 69, gcs: 8, temperature: 40.1, icp: 24 },
    isVentilatorConnected: true,
    icpCatheterRequired: true,
    clinicalNotes: 'Ceftriaxona 4g/d + dexametasona 0.15 mg/kg c/6h × 4d. LCR antes de ABT si no retrasa. Posición 30°. Osmoterapia si PIC > 20.',
    references: ['van de Beek D NEJM 2016', 'Brouwer MC Lancet 2012'],
  },
  // ── Anoxic Brain Post-Arrest ────────────────────────────────────────────────
  {
    id: 'anoxic_brain_post_arrest',
    category: 'neuro',
    name: 'Encefalopatía Anóxica Post-RCP',
    description: 'PCR extrahospitalaria por FV. RCP 22 minutos. ROSC. Inconsciente (GCS 5). TTMPC objetivo 36°C × 24h. Riesgo necrosis cortical global.',
    baseSeverity: 0.85,
    tags: ['Post-PCR', 'Encefalopatía', 'ROSC', 'TTM', 'ARM'],
    pathologyConfigs: [
      { domain: 'neuroCritical', subtype: 'anoxia', baseSeverity: 0.85 },
      { domain: 'cardio', subtype: null, baseSeverity: 0.55 },
    ],
    initialVitals: { heartRate: 78, systolicBP: 110, diastolicBP: 68, meanArterialPressure: 82, gcs: 5, temperature: 35.2, lactate: 5.8 },
    isVentilatorConnected: true,
    ventilatorPreset: { fio2: 0.40, peep: 6 },
    clinicalNotes: 'Evitar hipertermia (> 37.7°C). Mantener PaO₂ 94-98%. Evitar hipercapnia. Pronóstico neuroprotector a 72h (EEG, SSEP, NSE).',
    references: ['Lascarrou JB NEJM 2019 (TTM2)', 'Nolan JP Resuscitation 2021'],
  },
  // ── Guillain-Barré ──────────────────────────────────────────────────────────
  {
    id: 'guillain_barre_respiratory_failure',
    category: 'neuro',
    name: 'Guillain-Barré — Fallo Respiratorio',
    description: 'Síndrome de Guillain-Barré (variante AIDP) con debilidad ascendente hasta músculos respiratorios. CV < 15 mL/kg. Intubación electiva programada.',
    baseSeverity: 0.68,
    tags: ['Guillain-Barré', 'Polineuropatía', 'ARM', 'Plasmaféresis', 'IVIG'],
    pathologyConfigs: [
      { domain: 'neuroCritical', subtype: 'gbs', baseSeverity: 0.68 },
    ],
    initialVitals: { heartRate: 102, systolicBP: 130, diastolicBP: 80, meanArterialPressure: 97, gcs: 15, respiratoryRate: 28, spo2: 93 },
    isVentilatorConnected: true,
    ventilatorPreset: { fio2: 0.35, peep: 5, pressureSupport: 12 },
    clinicalNotes: 'IVIG 0.4 g/kg × 5d o plasmaféresis (equivalentes). Marcapasos si BAV avanzado. Heparina BPM profilaxis. Fisioterapia precoz.',
    references: ['Hughes RA Cochrane 2012 (IVIG vs PE)', 'van der Meché FA NEJM 1992'],
  },
  // ── Myasthenic Crisis ───────────────────────────────────────────────────────
  {
    id: 'myasthenic_crisis',
    category: 'neuro',
    name: 'Crisis Miasténica',
    description: 'Miastenia gravis severa con insuficiencia respiratoria. CV declinante. Sialorrea, disfagia, ptosis bilateral. Trigger: infección respiratoria intercurrente.',
    baseSeverity: 0.72,
    tags: ['Miastenia', 'Crisis', 'ARM', 'IVIG', 'Plasmaféresis'],
    pathologyConfigs: [
      { domain: 'neuroCritical', subtype: 'myasthenia', baseSeverity: 0.70 },
    ],
    initialVitals: { heartRate: 96, systolicBP: 145, diastolicBP: 88, meanArterialPressure: 107, gcs: 15, respiratoryRate: 32, spo2: 90 },
    isVentilatorConnected: true,
    ventilatorPreset: { fio2: 0.40, peep: 5 },
    clinicalNotes: 'Evitar succinilcolina (resistencia) y aminoglucósidos/fluoroquinolonas (bloqueo). IVIG o plasmaféresis + corticoides. Neostigmina IV en crisis colinérgica es CONTRAINDICADA.',
    references: ['Gilhus NE NEJM 2016', 'Patwa HS Neurology 2012 (AAN)'],
  },
  // ── Brain Death Protocol ────────────────────────────────────────────────────
  {
    id: 'brain_death_protocol',
    category: 'neuro',
    name: 'Protocolo Muerte Encefálica',
    description: 'Paciente con TCE grave evoluciona a ausencia de función cerebral. GCS 3T, reflejos del tronco ausentes, apnea confirmada. Familia informada. Protocolo ME.',
    baseSeverity: 0.99,
    tags: ['Muerte Encefálica', 'Donación', 'Protocolo', 'Apnea'],
    pathologyConfigs: [
      { domain: 'neuroCritical', subtype: 'brain_death', baseSeverity: 0.99 },
    ],
    initialVitals: { heartRate: 48, systolicBP: 88, diastolicBP: 52, meanArterialPressure: 64, gcs: 3, temperature: 36.4, urineOutput: 0.05 },
    isVentilatorConnected: true,
    ventilatorPreset: { fio2: 1.0, peep: 5 },
    clinicalNotes: 'Protocolo: 2 EEG isoeléctricos + test de apnea + reflejos tronco. Soporte hemodinámico para mantenimiento de órganos. Contactar coordinador de trasplante.',
    references: ['Kirschen MP CCM 2023', 'Greer DM JAMA 2020', 'Shemie SD CJA 2023'],
  },
  // ── Stroke MCA Decompression ────────────────────────────────────────────────
  {
    id: 'stroke_mca_decompression',
    category: 'neuro',
    name: 'ACV Isquémico MCA + Craniectomía',
    description: 'ACV maligno de arteria cerebral media izquierda en paciente de 52 años. Desviación línea media 8 mm. Post craniectomía descompresiva de emergencia.',
    baseSeverity: 0.80,
    tags: ['ACV', 'MCA', 'Isquémico', 'Craniectomía', 'ARM'],
    pathologyConfigs: [
      { domain: 'neuroCritical', subtype: 'stroke_mca', baseSeverity: 0.80 },
    ],
    initialVitals: { heartRate: 88, systolicBP: 158, diastolicBP: 90, meanArterialPressure: 113, gcs: 7, icp: 18, temperature: 37.3 },
    isVentilatorConnected: true,
    ventilatorPreset: { fio2: 0.45, peep: 5 },
    icpCatheterRequired: true,
    clinicalNotes: 'Post craniectomía: evitar HTA severa y hipotermia. Cuidado cutáneo colgajo. Anticoagulación diferida 2-4 semanas. Rehabilitación precoz.',
    references: ['Vahedi K Lancet Neurol 2007 (DESTINY)', 'Jüttler E NEJM 2014'],
  },
  // ── Anoxic Brain Post-Arrest ────────────────────────────────────────────────
  {
    id: 'refractory_icp_tumor',
    category: 'neuro',
    name: 'HIC Refractaria — Tumor Cerebral',
    description: 'Paciente con GBM conocido, deterioro agudo por edema perilesional masivo y sangrado intratumoral. GCS 8 con pupila anisocórica. Necesita escalonamiento terapéutico.',
    baseSeverity: 0.78,
    tags: ['Tumor Cerebral', 'GBM', 'Edema', 'PIC', 'Dexametasona'],
    pathologyConfigs: [
      { domain: 'neuroCritical', subtype: 'tumor_ic', baseSeverity: 0.78 },
    ],
    initialVitals: { heartRate: 58, systolicBP: 180, diastolicBP: 100, meanArterialPressure: 127, gcs: 8, icp: 26, temperature: 37.1 },
    isVentilatorConnected: true,
    icpCatheterRequired: true,
    clinicalNotes: 'Dexametasona 10mg IV inicial → 4mg c/6h (edema vasogénico). Manitol 1 g/kg. Oncología para decisión quirúrgica. PPC > 70 mmHg.',
    references: ['Wen PY NEJM 2020 (GBM management)'],
  },
];
